CONTRIBUTING.md
Url for commit samples should point to main, the default branch.
Closes #25
=> docs(contributing): correct samples url

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
This prevents errors when using the plugin with Astro/Playwright/etc because
the license comments trigger a build error
=> fix(vite-plugin-angular): always strip license comments from builds

packages/create-analog/__tests__/cli.spec.ts, packages/create-analog/index.js
When a new Analog project is created via `yarn create analog` or `pnpm create analog`, the start command will be `npm run dev`.
When a new Analog project is created via `yarn create analog` or `pnpm create analog`, the start command will be `yarn dev`/`pnpm run dev`.
=> feat(create-analog): set start command based on package manager

apps/docs-app/docusaurus.config.js
- Fixes #45 
Correct the edit URL path so that *Edit this page* links on the documentation website aren't broken.
=> docs: correct edit URL

apps/docs-app/src/pages/index.module.css, apps/docs-app/src/pages/index.tsx
**References**
- Closes #38 
**New Behaviour**
=> docs: fix styling for buttons on mobile

packages/create-analog/template-angular-v14/README.md, packages/create-analog/template-angular-v14/package.json
Hello,
- Closes #44 
- The default port is now `5173`
- The default host should be `localhost` but on Node.js under v17 it's displayed as `http://127.0.0.1:5173/`, what do you want to do ?
- Keep it like this
- Apply the workaround from the doc https://vitejs.dev/config/server-options.html#server-host
- Set minimum Node.js version to `17+`
- Vite no longer supports `Node.js 12 / 13 / 15`
- Should we set minimum Node.js version to `14.18+` / `16+` ?
=> chore(create-analog): update template application to latest dependencies

packages/create-analog/template-angular-v14/tsconfig.app.json, packages/create-analog/template-angular-v14/tsconfig.json, packages/create-analog/template-angular-v14/tsconfig.spec.json
=> fix(create-analog): add tsconfig references so IDE can recognise projects

packages/astro-angular/package.json
refactor: remove unnecessary peer dep
Removed @angular/forms from the peer deps array for the astro-angular package
Resolves #61
=> refactor: remove unnecessary peer dep

packages/astro-angular/src/client.ts
Right now the client side of the rendering doesn't check the ComponentMirror before setting the inputs of the angular component. Astro might add additional props that cause ng0303 error
Issue Number: #79 
Client rendering checks the ComponentMirror and sets the inputs only if they are defined on the component.
=> fix(astro-angular): check ComponentMirror before setting input 

packages/astro-angular/README.md
- Add missing `Input` import for the `HelloComponent` example.
- Remove `.ts` suffix for Angular component import in `.astro` file, astro VS Code extension complained about it
=> docs: update astro-angular example

packages/astro-angular/README.md
* add link to client directives
Issue Number: #90
=> docs: use component in mdx pages, closes #90

apps/astro-app/src/pages/index.astro, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Issue Number: #95
Inline scripts `type=script` passed through the transform are ignored. When using inline scripts with Astro, the script gets inline so it can pass through Vite's transform pipeline. This file isn't part of the Angular TypeScript compilation, but because it ends with a `.ts` extension, the transform tries to handle it.
This change ignores files like this that are provided the `type=script` as part of the query string on the filename.
=> fix(vite-plugin-angular): skip transforming inline scripts

packages/astro-angular/tsconfig.lib.json
Issue Number: #96
Warnings for sourcemaps are no longer shown when using the Angular integration with Astro
=> fix(astro-angular): inline sourcemaps into compiled output

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
change line 125 176 from tsx to ts, set plugin not try to compile tsx file. https://github.com/analogjs/analog/issues/100#issuecomment-1272601651
Issue Number: #100
1.fix #100 only comple .ts file
=> fix(vite-plugin-angular): update plugin to ignore tsx files

apps/analog-app/vite.config.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vite-plugin-angular/src/lib/component-assets-plugin.ts
This removes the workaround for Rollup warnings by removing the inline resource imports from the Angular Compilation.
=> fix: add plugin to remove inline resource imports

.gitignore, angular.json, apps/analog-app/src/server/routes/v1.ts, apps/analog-app/tsconfig.json, apps/analog-app/vite.config.ts, package.json, packages/platform/.eslintrc.json, packages/platform/README.md, packages/platform/package.json, packages/platform/project.json, packages/platform/src/index.ts, packages/platform/src/lib/analog-platform-plugin.spec.ts, packages/platform/src/lib/analog-platform-plugin.ts, packages/platform/tsconfig.json, packages/platform/tsconfig.lib.json, packages/platform/tsconfig.lib.prod.json, packages/platform/tsconfig.spec.json, packages/platform/vite.config.ts, tsconfig.base.json, yarn.lock
=> feat(create-analog): support for api routes

packages/platform/src/lib/vite-nitro-plugin.spec.ts, packages/platform/src/lib/vite-nitro-plugin.ts
=> fix: only use Nitro during serve, build

packages/astro-angular/README.md
Adds `"src/**/*.tsx"` to the example `tsconfig.app.json` config in the `astro-angular` README.md.
Issue Number: [128](https://github.com/analogjs/analog/issues/128)
=> docs(astro-angular): add tsx glob to example astro tsconfig.app.json

packages/vite-plugin-angular/package.json
The peer dependency `@angular-devkit/build-angular` supports only major version 14.
The peer dependency `@angular-devkit/build-angular` should also support major version 15.
=> fix(vite-plugin-angular): allow build-angular v15

packages/create-analog/template-angular-v15/package.json
Nx 15.4.x introduced a change that requires a project.json. This pins the Vite plugin to Nx 15.3.x to get the template app working again
=> fix(create-analog): pin @nrwl/vite package to 15.3.x

packages/create-analog/template-angular-v15/index.html, packages/create-analog/template-angular-v15/package.json, packages/create-analog/template-angular-v15/src/main.server.ts, packages/create-analog/template-angular-v15/tsconfig.app.json
- Adds support for SSR to the template application
- SSR in dev/build can be enabled with the `ssr` flag
```js
publicDir: 'src/assets',
build: {
target: ['es2020'],
},
resolve: {
mainFields: ['module'],
},
plugins: [
analog({ ssr: true })
],
test: {
globals: true,
environment: 'jsdom',
setupFiles: ['src/test.ts'],
include: ['**/*.spec.ts'],
},
define: {
'import.meta.vitest': mode !== 'production',
},
}));
```
=> feat(create-analog): add SSR support to v15 template app

apps/blog-app/vite.config.ts, packages/platform/src/lib/build-server.ts, packages/platform/src/lib/options.ts, packages/platform/src/lib/vite-nitro-plugin.ts
=> feat: update prerender option to discover and resolve routes

README.md, apps/docs-app/docs/introduction.md
The `@analogjs/content` was missing from the package list.
=> docs: add @analogjs/content to package list

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
To cover all possible use cases it's better to pass a whole `ts.CustomTransformers` object rather than just `before` tranformers
Closes #220
We pass only `before` object to custom transformers
Issue Number: #220 
Pass a whole `ts.CustomTransformers` object. An example from the original issue now should look like:
```ts
export default defineConfig(() => {
return {
plugins: [
analog({
advanced: {
tsTransformers: {
before: [customTransformer]
}
}
})
]
};
});
```
Additionally `after` and `afterDeclarations` could be passed as well.
=> feat(vite-plugin-angular): change tsTransformers parameter type

packages/router/src/lib/routes.ts
Markdown routes are loaded eagerly.
Markdown routes are loaded lazily.
=> fix(router): lazy load markdown routes

apps/blog-app/vite.config.ts, packages/content/src/lib/content-file.ts, packages/content/src/lib/content-files-list-token.spec.ts, packages/content/src/lib/content-files-list-token.ts, packages/content/src/lib/content-files-token.spec.ts, packages/content/src/lib/content-files-token.ts, packages/content/src/lib/content.spec.ts, packages/content/src/lib/content.ts, packages/content/src/lib/get-content-files.ts, packages/content/src/lib/get-raw-files.ts, packages/content/src/lib/inject-content-files.spec.ts, packages/content/src/lib/inject-content-files.ts, packages/content/src/lib/markdown.component.ts, packages/content/src/lib/utils/zone-wait-for.ts, packages/platform/src/lib/content-plugin.ts
Issue Number: #234 
Content files are lazy-loaded and not included in the main bundle. The content files list includes the filename and frontmatter attributes for lists.
=> feat(content): add support for lazy loading content files

apps/blog-app/src/app/routes/about.md, apps/blog-app/src/app/routes/blog.ts, apps/blog-app/src/app/routes/contact.md, packages/content/src/index.ts, packages/content/src/lib/content.ts, packages/content/src/lib/markdown-content-renderer.service.spec.ts, packages/content/src/lib/markdown-content-renderer.service.ts, packages/content/src/lib/markdown.component.ts, packages/content/src/lib/parse-raw-content-file.ts, packages/router/src/lib/markdown-helpers.ts, packages/router/src/lib/routes.ts
Closes #215
We can set `title` and `meta` tags for markdown routes:
```md
---
title: About
meta:
- name: description
content: About Page Description
---
Welcome!
```
```
BREAKING CHANGES:
`MarkdownComponent` no longer parses provided content using `front-matter`.
Instead, it expects the content body to be provided directly.
This breaking change will not affect cases where the `injectContent` result is passed
to `MarkdownComponent` because the `injectContent` function already parses
a raw content file and returns the content body.
```
=> feat(router): set title and meta tags for markdown pages

apps/docs-app/docs/packages/vite-plugin-angular/css-preprocessors.md, packages/astro-angular/README.md
stylus support for Angular has been deprecated since the release of [Angular 15.0.0](https://github.com/angular/angular-cli/releases/tag/15.0.0) and should not be listed anymore.
closes #243
Issue Number: #243
=> docs: remove stylus pre-processor

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vite-plugin-angular/src/lib/compiler-plugin.ts
Closes #139
Closes #2
The compiler plugin is created internally. This will mitigate problems when using Angular within other frameworks like Astro, Qwik because we're only running the angular-compiler on dependencies and not userland code. It also removes the processing of styles by the compiler plugin so styles are only compiled through Vite.
=> feat(vite-plugin-angular): inline esbuild compiler plugin

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vite-plugin-angular/src/lib/component-resolvers.spec.ts, packages/vite-plugin-angular/src/lib/component-resolvers.ts
Closes #257
Multiple occurrences of `templateUrl` in a single file trigger changes correctly for each template
=> fix(vite-plugin-angular): support watch mode for multiple templateUrls

packages/platform/src/lib/vite-nitro-plugin.ts, packages/vite-plugin-angular/src/lib/component-resolvers.spec.ts
Issue Number: #270
Current implementation causes paths like the following to be passed to nitro causing unhandled error:
```
"C:\\analog-personal-copy\\node_modules\\@analogjs\\platform\\src\\lib/runtime/api-middleware"
```
In windows `rootDir` and `__dirname` are paths with double backslashes `\\`. 
These are replaced with forward slash `/`.
closes #270
=> fix(platform): absolute paths must be valid file URLs on windows #270

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Build crashes when `process.env['NODE_ENV'] === 'test' || !!process.env['VITEST']` is `true` and `viteServer` is `undefined`.
The build won't crash when `viteServer` is `undefined`.
Exploring your repo about Playwright component testing and trying to avoid requiring users to install the [Vite plugin](https://github.com/brandonroberts/analog-playwright-component-tests/blob/main/playwright-ct.config.ts#L3) and specify [the tsconfig](https://github.com/brandonroberts/analog-playwright-component-tests/blob/main/playwright-ct.config.ts#L34).
Hence i'm setting `process.env['NODE_ENV']` environment variable to `'test'` so that the Vite plugin can resolve this by it self: …
=> fix: undefined viteServer

packages/create-analog/template-angular-v15/src/main.providers.ts, packages/create-analog/template-angular-v15/src/main.server.ts, packages/create-analog/template-angular-v15/src/main.ts
Fixes #285 
It doesn't contain a `main.providers.ts` file for common providers shared between the client and server.
It DOES contain a `main.providers.ts` file for common providers shared between client and server.
=> chore: create main providers file for generated app

packages/platform/src/lib/ssr/ssr-build-plugin.ts
Doing the replacement of `xhr2.XMLHttpRequest` to `xhr2.default.XMLHttpRequest` for esm support only happens once.
=> fix(platform): only transform xhr2 to default import one time

apps/analog-app/vite.config.ts, apps/blog-app/vite.config.ts, apps/docs-app/docs/features/server/server-side-rendering.md, packages/platform/project.json, packages/platform/src/lib/platform-plugin.spec.ts, packages/platform/src/lib/platform-plugin.ts
Instead of enabling SSR/SSG in the Analog config,
SSR/SSG would are now enabled by default for server-side support out of the box. SSR can still be disabled for client-only builds setting the ssr option to false.
Closes #294
Currently you need to enable SSR by setting the ssr option to true.
Issue Number: #294 
This change enables SSR by default and let's you opt out of it by setting the ssr option to false.
=> feat: enable ssr by default for analog platform plugin

packages/router/src/lib/routes.spec.ts, packages/router/src/lib/routes.ts
As commented at https://github.com/analogjs/analog/issues/273#issuecomment-1477800171, we need an adjust on the `replace` function to switch all `.` to `/` since by default only the first occurrence is replaced.
With a route file with name `route.[route-id].subroute.[subroute-id].ts`, Analog produces the route `route/:route-id].subroute.[subroute-id]`.
Now Analog produces the route `route/:route-id/subroute/:subroute-id` correctly.
=> fix(routes): fix nested dynamic routes path

packages/create-analog/__tests__/cli.spec.ts, packages/create-analog/files/postcss.config.js, packages/create-analog/files/styles.css, packages/create-analog/files/tailwind.config.js, packages/create-analog/index.js, packages/create-analog/package.json
User add tailwind to existing template via prompt or flag.
Closes https://github.com/analogjs/analog/issues/303
=> feat(create-analog): add tailwind gen to create-analog script

packages/nx-plugin/src/generators/app/files/versions.ts, packages/nx-plugin/src/generators/app/generator.spec.ts
=> fix(platform): update versions for Nx generators

apps/docs-app/docs/features/routing/overview.md
`ActivatedRoute` is being imported from `@analogjs/router` in the examples. This throws an error like:
```[ERROR] TS2305: Module "@analogjs/router" has no exported member 'ActivatedRoute'```
Correct import is from `@angular/router`.
=> docs(content): correct import of ActivatedRoute

apps/docs-app/docs/features/server/server-side-rendering.md, packages/vite-plugin-nitro/src/lib/vite-nitro-plugin.spec.data.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.spec.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Currently in the site plugin, if we just set the `ssr: true` (default behavior), the root route won't be served to the client. This can be achieved by setting the `{ pretender: {routes: ["/"] } }` array. The problem with this, that this is not covered in the documentation, and require some extra setup.
The point of the PR to add the `"/"` route to the routes array as default.
Also if the developer pass an empty array as argument, it won't be applied.
If they pass an array with values, this route won't be added to the array.
=> feat: add default pretender route

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
=> fix: only assign ngDevMode during build

packages/nx-plugin/generators.json, packages/nx-plugin/src/generators/app/files/tailwind/postcss.config.js__template__, packages/nx-plugin/src/generators/app/files/template-angular-v15/.eslintrc.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v15/tsconfig.app.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v15/tsconfig.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v15/tsconfig.spec.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v15/vite.config.ts__template__, packages/nx-plugin/src/generators/app/files/template-angular-v16/.eslintrc.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v16/tsconfig.app.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v16/tsconfig.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v16/tsconfig.spec.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v16/vite.config.ts__template__, packages/nx-plugin/src/generators/app/generator.spec.ts, packages/nx-plugin/src/generators/app/generator.ts, packages/nx-plugin/src/generators/app/lib/add-analog-dependencies.ts, packages/nx-plugin/src/generators/app/lib/add-analog-project-config.ts, packages/nx-plugin/src/generators/app/lib/add-files.ts, packages/nx-plugin/src/generators/app/lib/add-tailwind-config.ts, packages/nx-plugin/src/generators/app/lib/initialize-analog-workspace.ts, packages/nx-plugin/src/generators/app/schema.d.ts, packages/nx-plugin/src/generators/app/versions.ts, packages/nx-plugin/src/generators/preset/generator.spec.ts, packages/nx-plugin/src/generators/preset/generator.ts, packages/nx-plugin/src/generators/preset/schema.d.ts, packages/nx-plugin/src/generators/preset/schema.json, packages/nx-plugin/src/utils/version-utils.ts, packages/platform/package.json
The nx plugin now works without any manual addition of @nx/angular. You can create an empty workspace and simply add the @analogjs/platform dependency. After installing it you can run one command: nx g @analogjs/platform:app. This will automatically install all angular and analog dependencies. This plugin should also work as a preset for npx create-workspace. Since e2e testing for nx plugins is still a bit messy I tested this manually for now. It worked as expected for an empty package based and an empty integrated workspace as well as for an already preconfigured angular workspace.
Nx plugin required you to have your workspace already configured with angular.
Issue Number: #320
This …
=> feat: make nx plugin work without angular preset and add tailwind option

packages/astro-angular/migrations/migration.json, packages/astro-angular/package.json, packages/content/migrations/migration.json, packages/content/package.json, packages/platform/migrations/migration.json, packages/platform/package.json, packages/router/migrations/migration.json, packages/router/package.json, packages/trpc/migrations/migration.json, packages/trpc/package.json, packages/vite-plugin-angular/migrations/migration.json, packages/vite-plugin-angular/package.json, packages/vite-plugin-nitro/migrations/migration.json, packages/vite-plugin-nitro/package.json
New ng-update object was added to the package.json files for the @analogjs packages
Closes analogjs#360
Add `ng-update` property to the `package.json` in the platform page that contains the `packageGroup` with the packages that should be updated.
Currently there is no support for this feature.
Issue Number: 360
Now it will support the command, but currently there will be no rule to do any migration.
=> feat: add ng update support

apps/docs-app/docs/getting-started.md
Issue Number:  #320
This adds documentation for the Nx plugin to the getting started page.
Should I create a separate page for the plugin when not used as a preset?
=> docs(nx-plugin): add Nx plugin documentation to getting-started.md

apps/docs-app/docs/features/deployment/providers.md
We've had a release today: https://www.npmjs.com/package/@edgio/analogjs that now supports Analog with the latest Edgio v7 as well
=> docs: remove the version requirement from Edgio CLI

apps/docs-app/docs/features/deployment/overview.md, apps/docs-app/docs/features/deployment/providers.md, packages/vite-plugin-nitro/src/lib/build-server.ts
Adds the `BUILD_PRESET` environment variable as alternative to `NITRO_PRESET` for defining a server preset to use for Nitro.
=> feat(vite-plugin-nitro): add BUILD_PRESET as a server preset alias

apps/docs-app/docs/features/routing/overview.md
The current documentation example is missing the correct page suffix 
Add the page suffix to better comprehension
=> docs: add .page suffix on nested routes exemple

apps/analog-app/index.html, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Startup time is decreased by not forcing optimization of Angular packages
=> refactor: remove Angular libs from forced optimization

packages/content/src/index.ts, packages/content/src/lib/markdown-route.component.ts, packages/router/src/lib/markdown-helpers.ts
Closes #397 
Markdown files used as routes are statically prerendered
=> fix(content): add markdown route component for content routes

apps/trpc-app-e2e-playwright/tests/app.spec.ts, apps/trpc-app-e2e-playwright/tests/fixtures/notes.po.ts, apps/trpc-app/src/app/pages/index.page.ts, apps/trpc-app/src/server/trpc/context.ts, apps/trpc-app/src/server/trpc/routers/notes.ts, apps/trpc-app/src/server/trpc/trpc.ts, apps/trpc-app/src/trpc-client.ts, packages/trpc/src/lib/client/client.ts
A tRPCHeaders signal is exposed to set/get the headers added to each tRPC call. This allows us to, e.g. add an authorization header that we can then use to create protected procedures that can only be executed when the user is authorized.
closes #394
Closes #394 
You can provide custom headers to the trpc client by setting the tRPCHeaders signal
It works but I feel like the way we configure the tRPC client could be much better.
I think we should aim for a way to configure the tRPC client like @markostanimirovic allows the ngrx signal store to be configured. I want to get this merged because it is essential for anyone who wants to use the client for anything that is 
not public and the …
=> fix(trpc): allow to pass custom headers to trpc client

apps/docs-app/src/components/StackblitzButton/styles.module.css
Stackblitz link color on Safari is black in dark mode:
=> chore(docs): fix StackBlitz link color on Safari

packages/router/src/lib/inject-load.ts
When `injectLoad` is used within an Analog app with Angular v15, an error is throw because `assertInInjectionContext` is not available.
Closes #
No error is thrown for v15 projects.
=> fix(router): remove assertInInjectionContext check for v15 compatibility

CONTRIBUTING.md
While trying to come up to speed with Analog development I realized the contribution doc was out of date, mentioning `yarn` being used while the project has migrated to `pnpm`. This PR corrects the information on the manager to use, as well as addresses and adds other minor improvements based on Discord conversations.
Closes #
=> docs: update CONTRIBUTING.md for pnpm usage instead of yarn

README.md, package.json, packages/platform/src/lib/content-plugin.ts, packages/platform/src/lib/platform-plugin.ts, pnpm-lock.yaml
Closes #
The `@analogjs/content` package is already included with new projects, so this workaround is no longer needed.
=> refactor(platform): remove plugin to check for @analogjs/content package

package.json, packages/content/package.json, packages/content/src/lib/markdown-content-renderer.service.spec.ts, packages/content/src/lib/markdown-content-renderer.service.ts, packages/content/src/lib/marked-setup.service.ts, pnpm-lock.yaml
Fixed by adding the new extensions as well added a test
When serving the application and prerendering routes, a console warning is shown for the marked package
```
marked(): highlight and langPrefix parameters are deprecated since version 5.0.0, should not be used and will be removed in the future. Instead use https://www.npmjs.com/package/marked-highlight.
marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since …
```
=> fix(content): fix deprecation warnings for marked package

packages/content/src/lib/marked-setup.service.ts
Without the flag, pre-rendering hangs with more than a few posts
Noticed when pre-rendering lots of routes, the process runs out of memory.
Closes #
When pre-rendering lots of routes, the process finishes successfully
=> fix(content): add async flag to marked highlight config

apps/docs-app/docs/features/deployment/providers.md
Add documentation to specify a Node version when using render.com as well as documentation for hosting a static site
In setting up Render.com for my personal site, I got hung up on the build and deploy because the default node version was too low for Analog
Closes #
Add some new documentation for render.com setup as well as how to setup Render for static site hosting
=> docs: add additional render.com details

apps/blog-app-e2e-cypress/src/e2e/app.cy.ts, apps/blog-app/src/server/routes/rss.xml.ts, apps/blog-app/vite.config.ts, apps/docs-app/docs/features/api/overview.md, packages/vite-plugin-nitro/src/lib/runtime/api-middleware.js
Add the ability to set content-type as XJML in server routes and to have SSG correctly pre-render the data
When defining an API route with a `content-type` other than `applicaton/json`, nitro interprets all responses as `text/html` and renders a `.html` document for the data. If you would like to serve up something like XML for an RSS feed, this doesn't work.
If you set the headers to `content-type: text/xml` (or anything non-json) it re-proxies the request to allow nitro to interpret the result as intended.
Note: This is a bit wasteful to re-proxy the request, but I was unable to bet nitro to be happy with any other approach. I am totally willing to try other approaches, but this was …
=> feat(vite-plugin-nitro): add support for XML content in API routes

packages/trpc/src/lib/client/cache-state.ts
tRPC cache state is now active as long as the cache for the HttpClient is active in angular 16.1: Until the application is stable
Cache state is active indefinitely, which means that tRPC client never fetches a new request
Cache is only active while app is not stable. Then tRPC issues requests to the BE as expected.
Change is covered by e2e tests of the trpc-app. Currently, they are blocked by https://github.com/analogjs/analog/issues/468
=> fix(trpc): cache-state turns to inactive once app is stable

.github/workflows/ci.yml
The e2e suite fails on CI for the analog-app-e2e-cypress suite
Closes #
On my fork I was able to get this to correctly work. It looks like the [router configuration](https://github.com/analogjs/analog/blob/main/packages/router/src/lib/route-config.ts?plain=1#L39) blows up when this value is undefined correctly. Adding in a fallback value looks to make my local version happy. We will see how it does on this PR.
=> ci: fix e2e suite when running on ci

packages/vite-plugin-nitro/src/lib/vite-nitro-plugin.spec.data.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.spec.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
we change the output paths to be in a .vercel folder at the root of the workspace. this allows for zero config to be necessary when deploying analog with vercel
Need to manually adjust the build output for Vercel preset to use .vercel output API
Closes #491
Vercel presets work with 0 additional config necessary.
=> feat(vite-plugin-nitro): adjust output paths for vercel preset

package.json, packages/create-analog/package.json
Using `16.18` & `16.19` breaks Analog, let's retrains the version to the latest working Node16: `16.17`
Fixes #532
=> fix(create-analog): restrain node 16 to `16.17`.

packages/nx-plugin/generators.json
Just a small tweak so that the preset generator does not appear in Nx Console as it is not a generator intended to be run by the user directly (same as Nx do https://github.com/nrwl/nx/blob/master/packages/workspace/generators.json#L42C7-L42C21)
The preset generator is now hidden from Nx Console
=> fix(nx-plugin): hide preset generator from nx console

apps/docs-app/docs/features/deployment/providers.md
> remake of #544 because of branching issues on my side
Closes #493
=> docs: add Vercel deploypent provider info

apps/docs-app/docs/features/routing/overview.md
=> docs(router): add guide for route groups and pathless layouts

apps/blog-app/src/app/app.config.ts, apps/blog-app/src/content/2022-12-27-my-first-post.md, package.json, packages/content/migrations/migration.json, packages/content/package.json, packages/content/src/index.ts, packages/content/src/lib/markdown-content-renderer.service.ts, packages/content/src/lib/markdown.component.ts, packages/content/src/lib/marked-setup.service.ts, pnpm-lock.yaml
This commit add the support for mermaid diagrams in markdown content. 
About mermaid : https://mermaid.js.org/
About the exisit GitHub integration : https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/
I'll provide a doc update in a followup PR if this get's merged 👍
Closes #553
=> feat(content): add support for mermaid in markdown

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
This commit updates the implementation of the `handleHotUpdate` Vite plugin hook and includes a check to return if the `host` is not set. The `handleHotUpdate` hook may be called before the `buildStart` hook, which sets the compilation and the compiler host.
I've been having this error frequently:
=> fix(vite-plugin-angular): do not execute hot module update if host is not set

packages/router/src/lib/markdown-helpers.ts
Hey, I've just started experimenting with Analog and counting change detection cycles occurring in different scenarios due to the various asynchronous operations used in different parts of the code. I noticed that rendering a simple page, like `about.md` from the tutorial, causes 8 ticks immediately. This current commit updates the implementation of the `toMarkdownModule`, which loads `@analogjs/content` and `markdownFileFactory`, scheduling tasks in the root zone.
=> fix(router): do not run CD cycles unnecessary when markdown modules are loaded

apps/blog-app/src/app/app.config.ts, packages/content/src/index.ts, packages/content/src/lib/markdown-content-renderer.service.ts, packages/content/src/lib/markdown.component.ts
Using a separate provider for mermaid to allow treeshaking of the lib ! 
fixes #560
=> fix(content): make mermaid tree shakable

packages/nx-plugin/src/generators/app/generator.spec.ts, packages/nx-plugin/src/generators/app/lib/initialize-analog-workspace.ts, packages/nx-plugin/src/generators/app/versions/nx-dependencies.ts, packages/nx-plugin/src/generators/app/versions/nx_15_X/versions.ts, packages/nx-plugin/src/generators/app/versions/nx_16_X/versions.ts
currently the preset fails due to the @nx/linter dependency missing. this adds the dependency.
closes #567
preset fails. is missing.
Closes #567 
@nx/linter or @nrwl/linter are included as dependencies.
=> fix(nx-plugin): add linter dependency for nx app generator, preset

packages/nx-plugin/src/generators/app/generator.ts, packages/nx-plugin/src/generators/app/lib/add-eslint.ts
I barked up the wrong tree...
The issue stemmed from the nx-plugin being dependent on @nx/linter with the way it was set up. Instead, we are just creating a Nx workspace with the preset, which means the dependency is not installed. We need to import the @nx/linter dependency during runtime to avoid the preset to error out.
Even when forcing the @nx/linter dependency to be installed during the preset the execution fails. This is due to the nx-plugin having a direct
dependency on @nx/linter instead of importing it during runtime.
This time for real:
Closes #567
I am not sure exactly how to add a test for this? 
I thought the e2e test would catch this but it seems like it did not and …
=> fix(nx-plugin): remove dependency of nx-plugin to linter

packages/astro-angular/README.md
`,` (commas) are not allowed when listing dependencies.
=> docs(astro-angular): remove commas from list of `yarn add` dependencies

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Caching the template watchers causes issues when the component has multiple templateUrls
Closes #
Page reloads happen when external templates are changed, whether it be single or multiple.
=> fix(vite-plugin-angular): remove caching of watched component templates

apps/docs-app/docs/features/routing/content.md, packages/content/src/lib/content.spec.ts, packages/content/src/lib/content.ts
Closes #595
injectContent now supports a new argument { customFilename: string } that allows a hardcoded md file to be loaded from `/src/content`.
Example usage
```javascript
post$ = injectContent<PostAttributes>({ customFilename: 'index' });
```
Previously, if `injectContent` was used but a slug is not present, it will default to use `null.md`. Now, not providing a slug will throw an Error. Although breaking, this does not seem like intended behavior anyways.
=> feat(content): add customFilename param to injectContent

packages/vite-plugin-nitro/src/lib/build-sitemap.spec.ts, packages/vite-plugin-nitro/src/lib/build-sitemap.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.spec.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
When building the sitemap, the output directory uses a standard path. This would fail on Vercel as it outputs to a top-level directory.
Closes #
When building the sitemap, the output directory uses public output path.
=> fix(vite-plugin-nitro): pass public output path to sitemap builder

apps/docs-app/docs/features/testing/vitest.md, libs/top-bar/src/lib/top-bar/template.html, packages/vite-plugin-angular/src/lib/angular-jit-plugin.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Noticed in https://github.com/lacolaco/angular-vitest-sandbox that AOT mode must be enabled to handle external templates with inline comments and scripts correctly.
Closes #
JIT mode transforms the imports so they can be loaded with the raw loader in Vite, which correctly loads the external HTML file in Vitest. Also added some test script tags and comments in the top-bar unit test.
https://github.com/lacolaco/angular-vitest-sandbox
=> fix(vite-plugin-angular): use raw loader to handle external templates in jit mode

apps/docs-app/docs/features/api/overview.md
=> docs(router): add examples of API routes

packages/nx-plugin/src/generators/app/generator.spec.ts, packages/nx-plugin/src/generators/app/lib/add-analog-project-config.ts
The `outputs` array for a standalone project contains a period for each path. This now triggers a validation error with Nx.
Example: `dist/./analog-app/ssr`
Closes #
The `outputs` array for a standalone project does not contain a period for each path
Example: `dist/analog-app/ssr`
=> fix(nx-plugin): normalize outputs for standalone Nx projects

apps/analog-app/src/app/pages/(home).server.ts, apps/analog-app/src/app/pages/shipping/index.server.ts, packages/router/src/lib/route-types.ts, packages/vite-plugin-nitro/src/lib/plugins/page-endpoints.ts
Access to the `event` object from H3 is not available in the `load` function
Closes #606
Access to the `event` object from H3 is available in the `load` function. This allows you to set/read cookies, form data, and access other information derived from the event.
```ts
import { PageServerLoad } from '@analogjs/router';
import { parseCookies } from 'h3';
export function load({ event }: PageServerLoad) {
const cookies = parseCookies(event);
console.log('cookies', cookies);
return {
loaded: true,
};
}
```
=> feat(vite-plugin-nitro): add server event to load function and types

apps/docs-app/docs/features/routing/content.md, packages/content/src/lib/markdown-content-renderer.service.spec.ts, packages/content/src/lib/marked-setup.service.ts
=> feat(content): support prismjs diff highlight

apps/astro-app-e2e-playwright/tests/app.spec.ts, apps/astro-app/src/components/card.component.ts, apps/astro-app/src/pages/index.astro, packages/astro-angular/README.md, packages/astro-angular/package.json, packages/astro-angular/src/client.ts, packages/astro-angular/src/utils.ts
Component outputs are currently not supported.
Outputs from client-side hydrated Components can be listened to as a custom event using an utility function.
- Is `[data-analog-id]` the best property name for this?
- Are the caveats for making this work acceptable to release this feature? (only client-side, data attribute required, helper function to abstract some workarounds away)
=> feat(astro-angular): implement output forwarding on client-side hydrated components

package.json, packages/astro-angular/src/client.ts, packages/astro-angular/src/server.ts, packages/platform/src/lib/ssr/ssr-build-plugin.ts, packages/vite-plugin-angular/setup-vitest.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts, pnpm-lock.yaml
Closes #650 
Imports were updated to ensure compatibility with current and future versions.
=> fix(astro-angular,vite-plugin-angular): update zone.js deep imports for compatibility

packages/create-analog/template-angular-v16/package.json
Nx 16.9.1 is installed with `create-analog`
Closes #
Pins Nx packages to `16.8.1` until #667 is resolved
=> fix(create-analog): pin Nx packages to 16.8.1

apps/create-analog-e2e/tests/create-analog.spec.ts, packages/create-analog/template-angular-v16/angular.json, packages/nx-plugin/src/generators/app/lib/add-analog-project-config.ts
Closes #
- Adds an E2E test to run `create-analog` and upgrade to the `next` release of Angular to validate everything still works.
- Also adds the `tsConfig: "tsconfig.app.json"` property to new projects to ensure they can be upgraded without errors
=> test: add E2E test for create-analog with next release of Angular

apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current/getting-started.md, apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current/introduction.md
Closes #
Translate   `getting-started.md` and `introduction.md` to spanish
=> docs(content): add es translations for getting-started and introduction

packages/create-analog/template-angular-v16/package.json
Closes #
`@nx/vite` is pinned to `16.8.1` as it is currently incompatible when used in an Angular CLI workspace with Nx 17.
=> fix(create-analog): pin @nx/vite version to 16.8.1 for angular v16 template

apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current/getting-started.md
`run` is not required in `npm run start` https://docs.npmjs.com/cli/v10/commands/npm-start
=> fix(docs): simplify npm start command

packages/vite-plugin-nitro/src/lib/options.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.spec.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #
- The internal name for the plugin is correct
- The `index` option is passed to the dev server
=> fix(vite-plugin-nitro): update plugin name, pass options to dev server

packages/create-analog/template-angular-v16/src/main.server.ts, packages/create-analog/template-angular-v17/src/main.server.ts, packages/nx-plugin/src/generators/app/files/template-angular-v16/src/main.server.ts__template__
this solves an issue when libraries might rely on injecting dom elements, e.g. nx-scroll-bar, which causes the dev server to throw an error as these dom elements are not available during SSR. however, angular allows us to stub these elements on the server by importing @angular/platform-server/init.
Closes #664
Closes #664
Removes the need to add it manually.
=> fix(nx-plugin): add @angular/platform-server/init to main.server files

apps/docs-app/docs/features/testing/vitest.md
Added missing @nx/vite dependency to dev. installs.
- [x ] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ x] Documentation content changes
Incomplete documentation for installation of vitest into extant NG 17 project.
Closes #
Following the docs leads to successful installation of vitest.
- [ x] No
None.
=> docs: added missing dependency to development installations

packages/platform/src/lib/options.ts, packages/platform/src/lib/platform-plugin.ts, packages/vite-plugin-nitro/src/lib/options.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.spec.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
You can set the `workspaceRoot` for the vite plugin Angular, but not for the vite nitro plugin.
Adding a new `workspaceRoot` option to platform and vite nitro plugin. The platform option will automatically set it for both the angular and nitro plugins.
=> feat(vite-plugin-nitro): add `workspaceRoot` option to override `process.cwd`

packages/platform/src/lib/options.ts
The nitro plugin inherits the platform options, but the interface doesn't reflect this as the `index` option was missing.
You can see the index option in the options of the platform plugin
=> fix(platform): add missing `index` option for the platform plugin

apps/docs-app/docs/features/server/static-site-generation.md
=> docs(router): add guide on using postrenderhooks

apps/docs-app/docs/features/api/overview.md, apps/docs-app/docs/features/data-fetching/server-side-data-fetching.md
Closes #728
Add example to API routes on accessing cookies and remove some unwanted imports
=> docs(router): add cookies example

apps/docs-app/docs/features/testing/vitest.md, packages/create-analog/template-angular-v16/vite.config.ts, packages/create-analog/template-angular-v17/vite.config.ts, packages/nx-plugin/src/generators/app/files/template-angular-v16/vite.config.ts__template__, packages/nx-plugin/src/generators/app/files/template-angular-v17/vite.config.ts__template__, packages/nx-plugin/src/generators/setup-vitest/files/vite.config.ts__template__
If the `reporters` array is undefined, no reporters are added, causing the `ng test` command to run with no output.
Closes #
The `reporters` array is set to `['default']`, so terminal output is produced.
=> fix: add default reporters to vitest configuration

packages/vite-plugin-angular/src/lib/component-resolvers.ts
Closes https://github.com/analogjs/analog/issues/798
On Windows, path is: "C:UserProjectNameFrontsrcappapp.component.html?raw"
Path is: "C:/User/ProjectName/Front/src/app/app.component.html?raw"
best describes this PR or how it makes you feel?
=> fix(vite-plugin-angular): support Windows path for templateUrl and styleUrl

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #410 
Closes #86 
Provides empty `mappings` to suppress warning messages when using inline source maps. Still needs more investigation in terms of original source correctly mapping to the generated source and sourcemap
=> fix(vite-plugin-angular): improve compatibility with sourcemaps

packages/nx-plugin/src/generators/app/files/template-angular-v15/tsconfig.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v16/tsconfig.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v17/tsconfig.json__template__
Currently tests created in the `src/server` directory within an analog application scaffolded inside a Nx monorepo are not recognized. Similarly, tsconfig paths are not respected, causing import issues.
Closes #801
After conversation with @brandonroberts , making the `exclude` array in the `tsconfig.json` of the application an empty array fixes this as currently it is excluding all test files under `src/server`. An alternative is to override the `excludes` by setting an empty array in `tsconfig.spec.json`, but this only fixes the tests not being recognized, not the tsconfig paths issue.
=> fix(nx-plugin): fix server tests and tsConfigPaths not being recognized

packages/trpc/src/lib/client/client.ts, packages/trpc/src/lib/client/shared-internal.ts, packages/trpc/src/lib/client/trpc-rxjs-proxy.ts
Currently trying to build an analog application integrated with tRPC in the Nx monorepo setup fails due to type checks being run on the `@trpc/client` and `@trpc/server` npm packages. This is highlighting some transitive items that may be improved in trpc, but is highlighting that our trpc import references are not correct on our side. Namely, there are imports importing directly from the source files included in the trpc packages as opposed to importing from the library mapping or `dist` folder. This is leading to `skipLibChecks` not being respected.
Closes #722
The application can now be built without issue. No regressions as imports were updated to stop referencing the `src/` …
=> fix(trpc): remove imports to @trpc/client/src and @trpc/server/src

apps/analog-app/src/app/app.config.ts, apps/analog-app/src/app/interceptors/cookies.interceptor.ts, apps/analog-app/src/main.server.ts, packages/vite-plugin-nitro/src/lib/plugins/dev-server-plugin.ts, packages/vite-plugin-nitro/src/lib/runtime/renderer.js
PR adds full req and res object from h3 to the analog event handler for  app rendering
closes #802
closes #586 
- [ x] Feature
- [ x] vite-plugin-nitro
Current behavior is that the full, raw request and response are not provided to Analog, which limits the ability to use cookies from the incoming request. 
Closes #802 
Now both the runtime renderer event handler and the nitro dev server have access to the request and response, which can then be provided to the application.
- [x ] No
=> feat(vite-plugin-nitro): provide req and res to renderer

apps/ng-app/src/app/another-one.ng, apps/ng-app/src/app/app.component.ng, apps/ng-app/src/app/hello.ts, packages/vite-plugin-angular/src/lib/authoring/__snapshots__/ng.spec.ts.snap, packages/vite-plugin-angular/src/lib/authoring/ng.spec.ts, packages/vite-plugin-angular/src/lib/authoring/ng.ts
`let` variables that have their value assigned later do not work property if used on the template.
Closes #
`let` variables are supported by using `getters`. Late variables will still work if used on the template.
NOTE: even `let` is supported, it is recommended to use a reactivity model (signal or observable) if a variable is intended to be used on the template.
```html
<script lang="ts">
const cdr = inject(ChangeDetectorRef);
let lateVariable: string;
setTimeout(() => {
lateVariable = 'I am late';
cdr.detectChanges();
}, 2000);
</script>
<template>
@if (lateVariable) {
<h1>{{ lateVariable }}</h1>
}
</template>
```
becomes
```ts
export default class AnalogNgEntity {
constructor() { …
```
=> feat(vite-plugin-angular): support let with getters

apps/ng-app/src/app/export-stuff.ng, apps/ng-app/src/app/hello.ng, apps/ng-app/src/app/pages/about.page.ng, apps/ng-app/src/vite-env.d.ts, packages/vite-plugin-angular/src/lib/authoring/__snapshots__/ng.spec.ts.snap, packages/vite-plugin-angular/src/lib/authoring/ng.spec.ts, packages/vite-plugin-angular/src/lib/authoring/ng.ts
.ng format does not support defining a routeMeta
This allows adding a `route` configuration to `defineMetadata` e.g:
```ts
defineMetadata({
route: {
title: 'My page',
},
});
```
Happy to modify how this is supplied - this seemed the most natural to me (I have also extended the window type to include the `RouteMeta` type for `route`).
I assumed we didn't want to `export` the routeMeta in .ng files. Another option I considered was having a separate `defineRouteMetadata`
=> feat(vite-plugin-angular): add ability to export from .ng files

packages/astro-angular/src/server.ts
If a component has more than one selector when used with an Astro component, an error is thrown that it cannot find the root selector.
Closes #
If a component has more than one selector when used with an Astro component, the first selector is used to server render the component.
=> fix(astro-angular): use first selector for component tag on server render

apps/ng-app/project.json, apps/ng-app/vite.config.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Experimental support for `.ng` files was enabled through Analog
Closes #
Support for `.ng` files is removed
This was experimental in supporting an alternate way of authoring Angular components and directives. Despite various disclaimers, the `.ng` file associated causes too much confusion that this is an Angular team project that intends to replace the usage of class components in Angular.
=> fix(vite-plugin-angular): remove experimental support for .ng files

apps/ng-app/src/app/pages/about.page.analog, packages/vite-plugin-angular/src/lib/authoring/marked-setup.service.ts
When using common characters such as `@`, `{`, and `}` with `lang="md"` in code blocks, a template compilation error occurs. These are reserved symbols in an Angular template that should be escaped using HTML entities.
```html
<template lang="md">
'''sh
npm create analog
'''
'''ts
@Component({
selector: 'app-root',
})
class AppComponent {
doSomething() {}
}
'''
<Hello />
</template>
```
Closes #
When using common characters such as `@`, `{`, and `}` with `lang="md"` in code blocks, these characters are replaced with HTML entities. This reduces the compilation errors when using code blocks.
=> fix(vite-plugin-angular): escape common characters in code snippets for analog template

apps/ng-app/src/app/pages/posts.page.analog, apps/ng-app/src/content/post.agx, packages/content/src/lib/get-content-files.ts, packages/platform/src/lib/content-plugin.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vite-plugin-angular/src/lib/authoring/frontmatter.ts, packages/vite-plugin-angular/src/lib/host.ts
Markdown files can be used for content authoring, without support for Angular components
Closes #
The idea started in #448 by @joshuamorony 
This introduces support for `.agx` content files, which are similar to MDX files in that you can have markdown content with frontmatter, along with support for Analog and Angular component authoring syntax.
A similar project is [mdsvex](https://mdsvex.pngwn.io/) which enables this for Svelte components.
A `.agx` content file is transformed into a component file with 2 exports
- A default export for the compiled TypeScript code
- A `metadata` export for the associated frontmatter object
Example (post.agx)
```markdown
---
title: Hello World
--- …
```
=> feat: add initial support for agx content files

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vite-plugin-angular/src/lib/host.ts
Currently the glob used to find analog files only searches from the root of the application, this means in a workspace with multiple projects analog files outside of the application directory won't be found/compiled
Closes #
Add a configuration to `supportAnalogFormat` to allow supplying additional globs that will be applied from the workspace root. This will allow specifying specific libraries/directories to find analog files in as well as the app directory which is included by default.
=> feat(vite-plugin-angular): add include configuration for analog file globs

packages/vite-plugin-angular/src/lib/component-resolvers.spec.ts, packages/vite-plugin-angular/src/lib/component-resolvers.ts
Closes #797 
Uses AST instead of string matching/replacement to parse `templateUrl`s
=> fix(vite-plugin-angular): extract `templateUrl`s using AST

packages/vite-plugin-nitro/src/lib/runtime/api-middleware.js
- [ x ] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ - ] Tests for the changes have been added (for bug fixes / features)
- [ - ] Docs have been added / updated (for bug fixes / features)
- [ x ] Bugfix
- [ x ] vite-plugin-nitro
The HTTP headers are not tranmitted to the API endpoints.
Closes #
- [ x ] No
We are using cookies in our application, and there are some cases where cookies are not transmitted to the backend, during SSR rendering (for example, the default resolver doesn't transmit the cookies). The minimal modification we need for now is the one inside this PR.
=> fix(vite-plugin-nitro): forward HTTP headers to the API endpoint

packages/vite-plugin-angular/src/lib/authoring/__snapshots__/analog.spec.ts.snap, packages/vite-plugin-angular/src/lib/authoring/analog.ts
BREAKING CHANGE: This PR removes `constantName` from the default selectors
`names` is imported from `nx/devkit` to derive different variations of the `componentName`. This forces Angular CLI users to install `nx` and `nx/devkit` to use `.analog` format.
Closes #
- No longer use `nx/devkit`
- The utilities of `names` are copied over
- `constantName` is removed from the default selectors
=> refactor(vite-plugin-angular): do not use names from nx/devkit

apps/ng-app/src/app/app.component.analog, apps/ng-app/src/app/pages/about.page.analog, packages/vite-plugin-angular/src/lib/authoring/__snapshots__/analog.spec.ts.snap, packages/vite-plugin-angular/src/lib/authoring/analog.spec.ts, packages/vite-plugin-angular/src/lib/authoring/analog.ts
Analog components need to be imported like this:
```ts
import Hello from './hello.analog' with { analog: 'imports' };
```
and can then be used like this:
```html
<Hello />
```
I think this creates the false perception that the name of the default import is relevant, when it isn't actually used at all to determine the components selector. If we change the default import name:
```ts
import HelloComponent from './hello.analog' with { analog: 'imports' };
```
```html
<HelloComponent />
```
This will not work. I think this is surprising behaviour, and second to that since we don't actually need the default import name it is unnecessary boilerplate.
This PR allows importing analog components …
=> feat(vite-plugin-angular): allow analog imports with no name

apps/ng-app/src/app/app.component.analog, apps/ng-app/src/app/pages/about.page.analog
The example `ng-app` uses the non-standard format for importing `.analog` components:
```ts
import './hello.analog' with { analog: 'imports' };
```
Uses standard imports for examples:
```ts
import Hello from './hello.analog' with { analog: 'imports' };
```
(one example is left using no default import name)
=> refactor(vite-plugin-angular): use standard imports for ng-app examples

packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
In windows pre rendering fails due next error
```
[nitro] [request error] [unhandled] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:' 
```
Closes https://github.com/analogjs/analog/issues/688
=> fix: add file protocol to solve windows pre rendering issues

packages/vite-plugin-angular/src/lib/authoring/analog.ts
If an analog/agx file contains a number, e.g:
```
01-lesson-one.agx
02-lesson-two.agx
03-lesson-three.agx
```
The number will be used in the generated class name and will cause `ts-morph` to fail
Numbers are stripped when generating class names
=> fix(vite-plugin-angular): remove numbers at beginning in toPropertyName

packages/vite-plugin-angular/src/index.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vite-plugin-angular/src/lib/authoring/markdown-transform.ts, packages/vite-plugin-angular/src/lib/host.ts
When using Analog markdown templates, the analog markdown templates use marked and Prism to transform and add syntax highlighting.
Closes #
When using Analog markdown templates, the analog markdown templates can be transformed by using custom markdown template transform functions.
```ts
plugins: [
analog({
vite: {
experimental: {
supportAnalogFormat: true,
markdownTemplateTransforms: [
(content: string, fileName: string) => {
if (!fileName.includes('.analog') {
return content;
}
// use …
```
=> feat(vite-plugin-angular): add pipeline to transform analog markdown template

packages/vite-plugin-angular/src/lib/authoring/analog.ts
Similar to https://github.com/analogjs/analog/pull/919
When attempting to create a component using a `.agx` file:
```
import(
`../../../content/modules/lessons/angular-getting-started/01-generating-angular-app.agx`
).then((m) => {
divPost().createComponent(m.default);
cdr.detectChanges();
});
```
It will fail if the file name begins with numbers, as this is used to generate a selector for the component of `01-generating-angular-app` and then `createComponent` will try to use that as the tag name but it is invalid.
This change strips any leading numbers/hyphen from the selector generated from the file name, so `01-generating-angular-app.agx` would result in a selector of …
=> fix(vite-plugin-angular): remove numbers from beginning of file name selector

apps/ng-app/src/content/post.agx, packages/vite-plugin-angular/src/lib/authoring/marked-setup.service.ts
We escape potentially breaking characters for code blocks in the `MarkedSetupService` but not for single backtick codespans.
This caused a situation where if you have something like this in an agx file:
```
You will need to import from `@angular/fire`
```
It will cause a JIT compilation error because the `@` is never escaped.
The logic for escaping characters has been abstracted and is used for both `code` and `codespan` when setting up marked now.
=> fix(vite-plugin-angular): escape breaking characters for codespan

apps/ng-app/src/app/pages/about.page.analog, apps/ng-app/src/content/post.agx, packages/vite-plugin-angular/src/lib/authoring/marked-setup.service.ts
If attempting to use an Angular component that uses non-standard HTML syntax (e.g. expression bindings):
```html
<Hello [text]="greeting" />
```
The marked renderer will escape the HTML entities and it will be displayed as text rather than rendering the component. Control flow syntax kind of works as is but marked also encapsulates this syntax inside of paragraph tags, e.g:
Detection has been added for paragraphs that are any HTML/Angular component (e.g. it starts with `<` and ends with `/>`). In this case, the escaping of HTML entities will be reversed.
We also need to detect control flow syntax statements (e.g. starts with `@for`, ends with `}`) for two reasons:
1) It prevents the …
=> feat(vite-plugin-angular): support components and control flow in markdown

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
We extract the `vite:css` plugin during build to transform inline CSS. The function call do to the transform wasn't including the correct scope, causing an issue in Vite 5.1+.
Closes #969
The plugin transform is called with the correct plugin scope.
=> fix(vite-plugin-angular): bind css transform to correct plugin scope

apps/ng-app/project.json, apps/ng-app/src/app/hello.analog.spec.ts, apps/ng-app/src/test-setup.ts, apps/ng-app/tsconfig.spec.json, apps/ng-app/vite.config.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vite-plugin-angular/src/lib/host.ts
Analog SFCs cannot be used with the TestBed. In test mode, the compiler host is not patched to enable SFC support.
Closes #
Analog SFCs can be used with the TestBed. This forces disabling of JIT mode, so the compiler host is patched correctly to emit SFCs to JavaScript.
=> fix(vite-plugin-angular): add support for testing Analog SFCs

apps/docs-app/sidebars.js
Closes #947
I will be doing other revamps to this document, but for the time being this just adds it to the sidebar
=> docs: mention Vite in integrations sidebar

packages/vite-plugin-nitro/src/lib/build-ssr.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #960 
Enables support for Analog to be used with Nx and Project Crystal, as the paths are resolved correctly when providing a custom `workspaceRoot` to the analog plugin.
To use Project Crystal
- Add the Nx Vite plugin configuration to the `nx.json` - https://nx.dev/nx-api/vite#nxvite-configuration
- Remove the existing serve, build, test targets from the project.json
- Configure the analog plugin with a custom `workspaceRoot` imported from `@nx/devkit`
```ts
import { workspaceRoot } from '@nx/devkit';
export default defineConfig(({ mode }) …
```
=> feat: add support for Nx w/Project Crystal setup

.github/workflows/ci.yml
Currently pull requests ci builds are ran to completion even if build is outdated.
This cancels old queued builds on a retrigger
When accepting pull request suggestions.  Each accepted suggestion is executed to completion.
Old queued builds for a pull request are canceled. Only the latest retrigger is executed.
=> ci: cancel in progress pull request ci builds on retrigger

apps/docs-app/docs/experimental/sfc/index.md, apps/docs-app/docs/experiments/sfc/index.md, apps/docs-app/sidebars.js
I noticed that there were no docs for using the `.analog` extension.
This PR adds in initial documentation for the Analog SFC format. It denotes the extension as being experimental, but otherwise outlines how to use the extension
=> Document Analog SFC Usage

packages/vite-plugin-nitro/src/lib/runtime/api-middleware.ts
API routes created with `defineEventHandler` don't have access to platform-specific fields that get added to the `h3` event context when using various build presets (my specific use-case of concern is the `cloudflare-pages` preset)
Closes #1006
The `event.context` object is now forwarded along to api route handlers created with `defineEventHandler`.
=> fix(vite-plugin-nitro): retain event context when fetching API routes

apps/docs-app/docs/features/deployment/overview.md, packages/router/src/lib/route-config.ts
url.pathname ignoring path defined in env flag: VITE_ANALOG_PUBLIC_BASE_URL.
fixes: #954
Closes #954
=> fix(router): server-side-data-fetching when using basehref

apps/ng-app/src/app/pages/posts.[slug].page.analog, apps/ng-app/src/app/pages/posts.page.analog, apps/ng-app/src/content/mdpost.md, apps/ng-app/src/content/post.agx, packages/content/src/lib/content-file.ts, packages/content/src/lib/content-files-token.ts, packages/content/src/lib/content.spec.ts, packages/content/src/lib/content.ts, packages/content/src/lib/get-content-files.ts, packages/content/src/lib/markdown.component.ts
Using a `.agx` file currently requires manually importing/creating the component, e.g:
```ts
defineMetadata({
queries: {
divPost: new ViewChild('post', { static: true, read: ViewContainerRef }),
}
});
let divPost: ElementRef<HTMLDivElement>;
const cdr = inject(ChangeDetectorRef);
afterNextRender(() => {
const postId = 'post';
import(`../../content/${postId}.agx`).then(m => {
divPost.createComponent(m.default);
cdr.detectChanges();
});
});
```
`.agx` files can be used in the same manner as `.md` files with `injectContent`, e.g:
```ts
const post$ = injectContent({
customFilename: 'post'
});
const post = toSignal(post$)
```
```html
<analog-markdown …
```
=> feat(content): add agx support for injectContent

packages/vite-plugin-nitro/src/lib/build-server.ts, packages/vite-plugin-nitro/src/lib/runtime/renderer-client.mjs, packages/vite-plugin-nitro/src/lib/runtime/renderer-client.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.spec.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts, packages/vite-plugin-nitro/tsconfig.lib.json
When setting `ssr: false` in the analog plugin config, the client build output isn't produced in the `dist/analog/public` folder.
Closes #
- When setting `ssr: false` in the analog plugin config, the client build output is still produced in the `dist/analog/public` folder by default. 
- Prerendered routes are rendered as CSR-only HTML files.
- Running the built server serves the app with a fallback to CSR-only mode.
=> fix(vite-plugin-nitro): produce consistent builds for CSR mode

packages/vite-plugin-angular/src/lib/component-resolvers.spec.ts, packages/vite-plugin-angular/src/lib/component-resolvers.ts
Closes #1019
We account in backticks for templateUrl, styleUrl and styleUrls!
because the tests on component-resolver were always failing without me making any changes as I am on Windows so normalizePaths contains the drive letter in them.
=> fix(vite-plugin-angular): support backticks with templateUrl and styleUrls

apps/docs-app/docs/experimental/sfc/index.md
Using `analog` as a tag type does not highlight the example code on https://analogjs.org/docs/experimental/sfc#host-metadata
Using `html` is fixing that issue.
Using `analog` as a tag type does not highlight the example code on https://analogjs.org/docs/experimental/sfc#host-metadata
Using `html` is fixing that issue.
=> docs: use correct syntax highlighting tag type

packages/create-analog/index.js
Fixes `yarn dev` script error due to missing peer dependencies installation
When using `yarn` as the package manager, an exception is thrown while running `yarn dev`. This happens because `yarn` doesn't install the peer dependency.
Closes #1045 
Adds the missing dependency
=> fix(create-analog): add dev dependency when using yarn

apps/docs-app/docs/features/server/static-site-generation.md, packages/platform/src/lib/options.ts
The documentation wasn't obvious that we can pass not just a direct path, but a glob pattern too to this property
Closes #
=> docs(platform): add glob pattern to the contentDir value

packages/vite-plugin-angular/src/lib/utils/compiler-plugin-options.ts, packages/vite-plugin-angular/src/lib/utils/devkit.ts
Closes #
Angular v18 introduces a new `@angular/build` package and some of the esbuild tooling files have moved into the `@angular/build/private` export. This adds conditional imports based on the major version of Angular to continue to support multiple versions.
=> fix(vite-plugin-angular): use conditional imports across Angular Devkit versions

packages/vite-plugin-angular/src/lib/angular-vitest-plugin.spec.ts, packages/vite-plugin-angular/src/lib/angular-vitest-plugin.ts
Do not override `test.pool` option if it is already set by the user.
Closes #937
=> fix(vite-plugin-angular): honour user's test.pool choice

packages/vite-plugin-angular/esbuild.ts
`analogSFC` is not configurable
Allows supplying optional options object to `analogSFC` (uses existing default value if none is supplied)
=> feat(vite-plugin-angular): allow passing options to analogSFC esbuild plugin

apps/docs-app/docs/guides/compatibility.md, apps/docs-app/docs/guides/migrating.md, packages/platform/src/lib/router-plugin.ts
The `@analog/platform` package throws an error when used with Angular v15 because it tries to optimize `@angular/core/rxjs-interop` package which doesn't exist.
Closes #
The `@analog/platform` is compatible with Angular v15. Compatibility guides have also been updated.
=> fix(platform): add support in @analogjs/platform for older Angular versions

apps/docs-app/docs/features/deployment/providers.md
Some content exclusive to Nx in Vercel provider documentation is not in the Nx tab.
For non Nx users, the information is off-topic by being displayed by default.
Closes #
The content has been moved in the Nx tab.
😀
=> docs: move nx content in the related tab item

packages/nx-plugin/src/utils/versions/dependencies.ts, packages/nx-plugin/src/utils/versions/dev-dependencies.ts, packages/nx-plugin/src/utils/versions/ng_16_X/versions.ts, packages/vite-plugin-nitro/src/lib/vite-nitro-plugin.spec.data.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.spec.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
When using the `nitro.rollupConfig` options, the config wasn't being merged correctly.
Related to #977 
All Nitro customization options passed through `nitro` are merged correctly.
=> fix(vite-plugin-nitro): correctly merge Nitro config customizations

apps/docs-app/docs/features/routing/content.md
Closes #1014 
A new Example added to the docs.
=> docs: added example in docs of using a resolver for metatags for markdown component (#1014)

packages/vitest-angular/package.json
Closes #1112
This should resolve the related bug when attempting to install the `@analogjs/vitest-angular` package.
I'm not 100% certain how to test this fix myself, but GPT-4o tells me this is new pattern should satisfy the correct versioning conventions that would enable the package to be properly installed.
=> fix(vitest-angular): update peerDependencies for @angular-devkit/architect version pattern range

packages/content/package.json, packages/create-analog/template-blog/package.json, packages/create-analog/template-latest/package.json
Dependency errors on missing peer dependencies of unused highlighters.
Should not have dependency errors on missing peer dependencies of unused highlighters.
`mermaid` is also removed from the `@analogjs/content` peer dependencies because it is not a peer dependency.
=> fix(content): adjust peer dependencies meta for different highlighters

packages/router/src/lib/models.ts
Closes #1130 
Able to pass functional guards from @angular/fire
=> feat(router): add support for @angular/fire guards

packages/astro-angular/package.json, packages/content/package.json, packages/platform/package.json, packages/router/package.json, packages/trpc/package.json, packages/vite-plugin-angular/package.json, packages/vite-plugin-nitro/package.json, packages/vitest-angular/package.json
Refs: #1123
nx migrate failes with cannot find package @analogjs/trpc@v1.4.0
Closes #1123 
nx migate works
=> build: fix migrate by removing @analogjs/trpc from packageGroup

packages/vite-plugin-nitro/src/lib/plugins/dev-server-plugin.ts
If a [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) is returned instead of an HTML string, the development server throws an error.
Closes #
If a [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) is returned, it is handled and sent using the `sendWebResponse` utility method from `h3` that handles headers/cookies/etc.
=> fix(vite-plugin-nitro): handle web Response object in dev server plugin

README.md, packages/create-analog/index.js, packages/create-analog/template-blog/_gitignore, packages/create-analog/template-blog/package.json, packages/create-analog/template-latest/_gitignore, packages/create-analog/template-latest/package.json
Closes #
- Fixes issue where package.json versions were being set incorrectly when using `yarn`
- Vite version mismatch causes an error to be logged to the console. The Angular CLI is on version `5.2.x`, while the latest current version is `5.3.0`
=> fix(create-analog): correctly set package versions for yarn and pin Vite

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Sourcemaps were not working correctly.
Closes #86 
Closes #1147 
Closes #822 
- Sourcemaps are working correctly if esbuild is disabled. If the user provides a custom esbuild config, it is respected.
- Sourcemaps are working for `.analog` files
- Breakpoints are working correctly in the browser devtools
=> fix: disable esbuild if not configured to enable correct sourcemaps

apps/docs-app/docs/features/testing/vitest.md
I tried to copy the code and noticed that it didn't compile, technically it is marked with `...` but still this makes it somewhat easier to use.
=> docs: make vitest test code compile for easy copy-paste

packages/vite-plugin-angular/setup-vitest.ts, packages/vitest-angular/setup-zone.ts
Currently, when zones are wrapping the test function the context is lost causing an error "Cannot read `withContext()` of undefined".
Closes #1115
The original fn contains the mentioned `withContext()` method. I added reference to the initial method to the bounding function in order to preserve context.
I'm not sure how to properly test this change. I did not find tests for `setup-vitest`. I also failed to test this package using `npm link` as it failed complaining 
```
failed to load config from /Users/crush/Projects/analog-vitest-repro/apps/analog-vitest/vite.config.mts
Error: Cannot find module '@angular/build/private'
```
The original fix was found by tinkering the …
=> fix(vite-plugin-angular): prevent context loss for "each" tests

packages/router/src/lib/routes.spec.ts, packages/router/src/lib/routes.ts
Closes #1129 
Show a console.warn when default export is missing from component
=> fix(router): add error message when default export is missing from component

packages/nx-plugin/src/generators/setup-vitest/lib/update-tsconfig.ts
Add "vitest/globals" to types, and remove jest from the existing types.
When the `tsconfig.spec.ts` is updated the types are missing "vitest/globals" type which leads to in-editor errors.
1. The "vitest/globals" is added to the list of types
2. The type "jest" is removed from the array if it was previously there (a small improvement of life when migrating)
=> fix(nx-plugin): add vitest types in tsconfig.spec.json

packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #
The sitemap is built before the server is built, allowing the sitemap to be served through SSR requests.
=> fix(vite-plugin-nitro): make sitemap available for SSR build

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, MAINTAINER.md
Closes #1067 
Contributing guide is more straightforward and maintainer-specific docs have been moved to `MAINTAINER.md`
=> docs: simplify contributing docs and move some to maintainer guide

packages/content/prism-highlighter/src/index.ts, packages/content/prism-highlighter/src/lib/prism-highlighter.ts, packages/content/prism-highlighter/src/lib/prism/angular.js
Closes #1203 
By default, all markdown rendering and syntax highlighting are done at build time. This exports the `PrismHighlighter` to be used with `withHighlighter({ useClass: PrismHighlighter })` for custom client side markdown rendering and syntax highlighting.
```ts
export const appConfig: ApplicationConfig = {
providers: [
provideContent(
withMarkdownRenderer(), 
withHighlighter({ useClass: PrismHighlighter })
),
{ provide: ContentRenderer, useClass: MarkdownContentRendererService },
MarkedSetupService,
],
};
```
=> fix(content): export prism highlighter for custom client rendering

packages/router/src/lib/routes.spec.ts, packages/router/src/lib/routes.ts, packages/router/vite.config.ts
Closes #
No longer logs a warning for page routes used only for redirects
=> fix(router): skip default export warning for redirect page routes

package.json, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, pnpm-lock.yaml
Closes #1166 
Instead of using Vite's PluginContainer transform, which isn't meant to be used externally, switch to the standalone `preprocessCSS` utility function from Vite's public API when processing Component decorator styles. This ensures consistency across development and production, and relies less on internal APIs changing.
This allows Analog projects to use Vite 5.3.x
=> fix(vite-plugin-angular): use Vite preprocessCSS function for component decorator styles

packages/create-analog/template-blog/package.json, packages/create-analog/template-latest/package.json
Closes #
Unpins Vite from 5.2.x in the template apps
=> fix(create-analog): update templates to use Vite 5.x

packages/create-analog/index.js
Closes #
The expected values for the content highlighter are shiki or prism but the create-analog package adds 'prismjs'.
=> fix(create-analog): typo on prism highlighter

packages/astro-angular/src/index.ts
Closes #
- Fixes a bug where using Analog with Angular and Astro produces an error because the Analog Vite plugin for Angular disables esbuild if its not configured by default.
=> fix(astro-angular): pass Astro/Starlight defaults for esbuild

apps/analog-app/.env, apps/analog-app/src/app/app.config.ts, apps/analog-app/src/app/cart.service.ts, apps/analog-app/src/main-cf.server.ts, apps/analog-app/src/main.server.ts, apps/analog-app/vite.config.ts, apps/docs-app/docs/features/data-fetching/overview.md, apps/docs-app/docs/features/data-fetching/server-side-data-fetching.md, apps/docs-app/docs/features/deployment/providers.md, apps/docs-app/sidebars.js, packages/create-analog/template-blog/src/app/app.config.server.ts, packages/create-analog/template-blog/src/app/app.config.ts, packages/create-analog/template-blog/src/main.server.ts, packages/create-analog/template-latest/src/app/app.config.server.ts, packages/create-analog/template-latest/src/app/app.config.ts, packages/create-analog/template-latest/src/main.server.ts, packages/router/server/ng-package.json, packages/router/server/src/index.ts, packages/router/server/src/provide-server-context.ts, packages/router/src/index.ts, packages/router/src/lib/request-context.ts, packages/router/src/lib/route-config.ts, packages/router/tokens/ng-package.json, packages/router/tokens/src/index.ts, packages/router/tsconfig.lib.json, tsconfig.base.json
Closes #844
Closes #995 
Closes #1182
- Adds the `provideServerContext` provider function from `@analogjs/router/server`
- Adds the `injectBaseURL()`, `injectRequest()`, and `injectResponse()` functions from `@analogjs/router/tokens`
- Adds the `requestContextInterceptor` function that is environment aware when making HttpClient requests
By providing the server context, and request interceptor. Any HttpClient request that begins with a `/` is requested using the full URL on the server, client, and during prerendering without manually setting the `VITE_ANALOG_PUBLIC_BASE_URL` environment variable.
credit goes to @osnoser1 for the initial implementation 
```ts
// app.config.ts
import {
provideHttpClient,
withFetch,
withInterceptors,
} from '@angular/common/http';
import { ApplicationConfig …
```
=> feat(router): provide server context awareness to routing and HttpClient requests

packages/router/src/lib/provide-file-router.ts
Type casting for `provideRouter` result is not needed since Angular v16
🧹
=> refactor(router): remove unnecessary type casting

packages/create-analog/template-blog/src/app/pages/blog/[slug].page.ts, packages/create-analog/template-blog/src/app/pages/blog/index.page.ts
All components created for the blog template are named **HomeComponent**.
Closes #1236
Use proper names for components.
=> fix(create-analog): add proper component naming

packages/router/package.json, packages/vitest-angular/package.json
Closes #
- Allows the `@analogjs/vitest-angular` to install beta versions of `@analogjs/vite-plugin-angular`
=> fix: update peer dependencies for router and vitest-angular packages

packages/vite-plugin-angular/src/lib/angular-jit-plugin.ts
Closes #
Uses Vite's `preprocessCSS` for transforming CSS in JIT mode
=> fix(vite-plugin-angular): use Vite preprocessCSS function for JIT CSS transform

package.json, packages/platform/src/lib/ssr/ssr-build-plugin.ts, pnpm-lock.yaml
Closes #
- Works around an issue with `global` being redefined when importing `zone.js/node` due to how Vite loads in modules during its SSR transform. Only impacts zone.js 0.14.5+ versions.
- Only replaces first occurrence
=> fix(platform): add workaround for redefined global in zone.js 0.14.5+

apps/blog-app/vite.config.ts, libs/shared/feature/src/content/test.agx, packages/platform/src/lib/platform-plugin.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
When attempting to use `.agx` files from directories listed in `additionalContentDirs` no default export is present, only the metadata export.
It seems like it is possible to workaround this without any changes by also adding the `additionalContentDirs` directories to the `supportAnalogFormat` `include` configuration, e.g:
```ts
additionalContentDirs: [
'/libs/shared/data-access/src/content',
],
vite: {
experimental: {
supportAnalogFormat: {
include: ['/libs/shared/data-access/src/content/**/*'],
},
},
},
```
But not having to duplicate this seems preferable to me.
Any directories listed in `additionalContentDirs` will be added to the globs for finding analog files automatically.
=> fix(vite-plugin-angular): add additionalContentDirs to analog globs

apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current.json, apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/guides/migrating.md
Fix 2 pages with inconsistent menu and title:
- https://analogjs.org/zh-hans/docs/features/deployment/providers
- https://analogjs.org/zh-hans/docs/guides/migrating
=> docs: fix the page with inconsistent menu and title

apps/analog-app/src/server/middleware/redirect.ts, apps/analog-app/tsconfig.app.json, apps/analog-app/tsconfig.json, apps/docs-app/docs/features/routing/middleware.md, apps/docs-app/sidebars.js, packages/create-analog/template-blog/tsconfig.app.json, packages/create-analog/template-latest/tsconfig.app.json, packages/vite-plugin-nitro/src/lib/plugins/dev-server-plugin.ts, packages/vite-plugin-nitro/src/lib/utils/register-dev-middleware.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #
Middleware in the `src/server/middleware` folder can be used in development.
This makes testing server-side auth/cookies/protected routes easier to implement.
The `src/server/middleware/**/*.ts` entry must be added to the `include` array in the `tsconfig.app.json`
=> fix(vite-plugin-nitro): support server middleware in development

packages/nx-plugin/src/generators/app/files/template-angular-v18/src/app/app.config.server.ts__template__, packages/nx-plugin/src/generators/app/files/template-angular-v18/src/app/app.config.ts__template__, packages/nx-plugin/src/generators/app/files/template-angular-v18/src/main.server.ts__template__
Closes #
When generating a new Analog app with Nx, server request context providers/interceptors are configured.
=> fix(nx-plugin): add server context to Nx generator template

packages/vite-plugin-angular/src/lib/angular-jit-plugin.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #1262 
The resolved vite config is passed to the `preprocessCSS` function
=> fix(vite-plugin-angular): use resolved config for CSS preprocessor

apps/analog-app/src/app/interceptors/cookies.interceptor.ts
Closes: None.
When the load server function runs, it does not have loaded cookies. This is because of https://github.com/angular/angular/issues/15730. Therefore, the original request object is injected to get the cookies.
* None.
😂
=> fix: cookie interceptor

apps/analog-app/src/app/app.config.ts, packages/platform/src/lib/platform-plugin.ts, packages/platform/src/lib/ssr/inject-html-plugin.ts
Closes #1165 
When SSR is enabled, the event replay script is injected into the `index.html` to support `withEventReplay()` for client hydration.
=> fix(platform): add support for event replay with SSR

packages/platform/src/lib/deps-plugin.ts
Closes #
Fixes an issue where packages that need SSR transform were not discovered when creating an Nx workspace using the Analog preset.
=> fix(platform): use workspace root when discovering packages for SSR transform

apps/docs-app/docs/introduction.md, apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current.json, apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/routing/content.md, apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/routing/middleware.md
add zh-hans doc for the new middleware page
Also fix an runtime error in dev environment as below:
=> docs: add zh-hans on middleware page

packages/content/src/lib/content.ts, packages/content/src/lib/utils/zone-wait-for.ts
Closes #1047 
All Analog packages run when Zoneless change detection is configured 
TODO
=> fix(content): initial support for running with Zoneless change detection

packages/create-analog/template-angular-v16/src/test.ts, packages/create-analog/template-angular-v17/src/test.ts, packages/create-analog/template-blog/src/test-setup.ts, packages/create-analog/template-latest/src/test-setup.ts, packages/nx-plugin/src/generators/app/files/template-angular-v15/src/test-setup.ts__template__, packages/nx-plugin/src/generators/app/files/template-angular-v16/src/test-setup.ts__template__, packages/nx-plugin/src/generators/app/files/template-angular-v17/src/test-setup.ts__template__, packages/nx-plugin/src/generators/app/files/template-angular-v18/src/test-setup.ts__template__, packages/nx-plugin/src/generators/init/test-files/src/test-setup.ts__template__
Closes #
When generating the testing setup, `@analogjs/vitest-angular/setup-zone` is used to setup zone.js for testing.
=> fix: update templates to use vitest-angular import for testing

packages/platform/src/lib/deps-plugin.ts
Closes #1296 
The `rxfire` package was being externalized during SSR package discovery. This prevents that so it can be transformed during SSR.
=> fix(platform): prevent rxfire package from being externalized during SSR

packages/trpc/src/lib/utils/wait-for.ts
- `pnpm test` ran successfully
- Tested the `trpc-app` to work in zoneless change detection including this patch
- Closes #1295
Now also the trpc package works, when running in zoneless change detection.
=> fix(trpc): support running with Zoneless change detection

apps/docs-app/docs/guides/migrating.md, packages/nx-plugin/src/executors/vite/schema.json, packages/nx-plugin/src/utils/versions/ng_18_X/versions.ts
Closes #1040
Closes #1241
- The `fileReplacements` property in the schema doesn't do anything. Removing it so it will show a validation error. 
- Docs have been added on setting up environments in the Analog migration guide https://analogjs.org/docs/guides/migrating
=> fix(nx-plugin): remove fileReplacements from vite build schema

packages/vite-plugin-angular/src/lib/angular-storybook-plugin.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #
- Adds an internal plugin to detect the storybook command and enable the storybook plugin for zero config usage
=> feat(vite-plugin-angular): add internal plugin to detect Storybook environment

apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current.json, apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/api/og-image-generation.md, apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/integrations/storybook/index.md, apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/support.md, apps/docs-app/i18n/zh-hans/docusaurus-theme-classic/navbar.json
add zh-hans on [support](https://analogjs.org/docs/support), [og image generation](https://analogjs.org/docs/features/api/og-image-generation) and [storybook](https://analogjs.org/docs/integrations/storybook) pages
=> docs: add zh-hans on support and og image page

packages/vite-plugin-angular/src/lib/authoring/constants.ts, packages/vite-plugin-angular/src/lib/authoring/markdown-transform.ts, packages/vite-plugin-angular/src/lib/host.ts
Markdown template transforms may want to perform some transformation based on some information in the front matter of a file, but currently only the content of the `<template>` tag is passed to the transform:
```ts
if (fileName.includes('virtual-analog:')) {
for (const transform of options.markdownTemplateTransforms || []) {
content = await transform(content, fileName);
}
}
```
In the code above, `content` is the contents of the `<template>`, but front matter is placed outside of the template tag.
The `content` passed to the transform will now have the front matter added to the beginning if it exists, such that is has the structure of a standard markdown file with front matter, e.g:
```
---
title: hello
---
```
This will be breaking for anyone using custom markdown transforms as the value …
=> feat(vite-plugin-angular): include frontmatter in markdown transform content

packages/router/src/lib/request-context.ts
… responseType from httpclient
Closes #1322
Allow HttpClient to support responses other than JSON in SSR
=> fix(router): add responseType in requestContextInterceptor for HttpClient

packages/vite-plugin-angular/src/lib/authoring/marked-setup.service.ts
these parameters are now enabled via separate npm packages. They're set to `false` here which means we don't need to do anything extra
Closes #
=> fix(vite-plugin-angular): remove deprecated parameter from marked

packages/nx-plugin/src/generators/app/files/template-angular-v15/.eslintrc.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v16/.eslintrc.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v17/.eslintrc.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v18/.eslintrc.json__template__
I've been having this error when I create an app with Nx 
```
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
An error occurred while processing files for the @nx/eslint/plugin plugin.
- apps/blog/.eslintrc.json: Failed to load plugin '@nx/nx' declared in '.eslintrc.json#overrides[0]': Cannot find module '@nx/eslint-plugin-nx'
Require stack:
- /Users/ngilyass/projects/confs/findRally/apps/blog/__placeholder__.js
Referenced from: /Users/ngilyass/projects/confs/findRally/apps/blog/.eslintrc.json
Error: Failed to load plugin '@nx/nx' declared in '.eslintrc.json#overrides[0]': Cannot find module '@nx/eslint-plugin-nx'
Require stack:
- /Users/ngilyass/projects/confs/findRally/apps/blog/__placeholder__.js
Referenced from: …
```
=> fix(nx-plugin): typo that causes Nx graph to crash

packages/vite-plugin-angular/src/lib/angular-build-optimizer-plugin.ts
Closes #
Noticed a bug where a minimal build using Zoneless/Vite was 222kb vs Angular CLI build was 99kb. Packages with no side effects were being processed correctly. This ensures the same optimization happens and reduces the bundle size.
=> fix(vite-plugin-angular): fix optimization bug with bundles w/o side effects

packages/vitest-angular/src/lib/vitest.impl.ts
Closes #1331 
Passing the `--config` option on the command line is processed correctly.
=> fix(vitest-angular): pass custom config file path to runner

packages/vite-plugin-angular/src/lib/angular-build-optimizer-plugin.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #
When doing a JIT build, the angular compiler should not be marked as side-effect free.
=> fix(vite-plugin-angular): mark @angular/compiler with sideEffects during jit build

apps/docs-app/docs/features/testing/vitest.md, packages/vitest-angular/README.md, packages/vitest-angular/project.json, packages/vitest-angular/setup-snapshots.ts, packages/vitest-angular/setup-zone.ts, packages/vitest-angular/tsconfig.lib.json
Closes #
- The `@analogjs/vitest-angular/setup-snapshots` import can be used with Zoneless testing.
- Updates docs for Zoneless applications
=> fix(vitest-angular): setup separate import for configuring snapshots

libs/card/vite.config.ts, packages/vite-plugin-angular/src/lib/angular-vitest-plugin.ts
Closes #
When using Vitest, files containing `@angular/cdk` imports are transformed to downlevel async/await to es2016 when using with zone.js
=> fix(vite-plugin-angular): add better support for angular/cdk in vitest browser testing

packages/nx-plugin/src/generators/app/generator.spec.ts, packages/nx-plugin/src/generators/app/versions/dependencies.ts, packages/nx-plugin/src/generators/app/versions/nx_16_X/versions.ts, packages/nx-plugin/src/generators/app/versions/nx_17_X/versions.ts, packages/nx-plugin/src/generators/app/versions/nx_18_X/versions.ts, packages/nx-plugin/src/utils/versions/dependencies.ts, packages/nx-plugin/src/utils/versions/ng_15_X/versions.ts, packages/nx-plugin/src/utils/versions/ng_16_X/versions.ts, packages/nx-plugin/src/utils/versions/ng_17_X/versions.ts, packages/nx-plugin/src/utils/versions/ng_18_X/versions.ts
Closes #
- When generating a new application, or running a migration to Analog, the `marked-mangle` dependency is added.
- Analog dependencies are also bumped
=> fix(nx-plugin): add marked-mangle to installed dependencies on new app/migration

apps/ng-app/src/app/models.ts, apps/ng-app/src/app/pages/posts.[slug].page.analog, apps/ng-app/vite.config.ts, package.json, packages/vite-plugin-angular/package.json, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vite-plugin-angular/src/lib/authoring/frontmatter.ts, packages/vite-plugin-angular/src/lib/authoring/markdown-transform.ts, packages/vite-plugin-angular/src/lib/host.ts, pnpm-lock.yaml
I've taken the liberty of experimenting with a solution for this, so of course feel free to disregard if the approach/API isn't appropriate. Happy to make changes as required too.
Currently with `agx` files the frontmatter export is created before the markdown template transforms run, which is fine, but when the transform functions run they might want to add `vfile` data (as is the case with some remark/rehype plugins e.g. I have created some plugins that track word count/headings through vfile data)
At the moment when a markdown template transform is run it might return all the data as a vfile, e.g:
```ts
VFile {
cwd: '/Users/joshuamorony/Dev/projects/oss/analog-stuff',
data: {},
history: [],
messages: [],
value: '<h2>Test</h2>\n' +
'<p>Hello</p>\n' +
'<ul>\n' +
'<li>one</li>\n' + …
```
=> fix(vite-plugin-angular): allow supplying and exporting vfile data for agx files

packages/platform/src/lib/deps-plugin.ts
Related to https://github.com/taiga-family/taiga-ui/issues/9085
When using `@ng-web-apis` or `@taiga-ui` packages, no errors are thrown when using SSR. Our dependency crawler plugin doesn't account for peer dependencies inside top-level packages, so some of the packages were not being transformed for Angular compilation. 
Manually this was fixed by adding those orgs to the `ssr.noExternal` array in the `vite.config.ts`
```ts
ssr: {
noExternal: [
'@analogjs/trpc',
'@trpc/server',
'@ng-web-apis/**', // <-- transform all `@ng-web-apis` sub-packages
'@taiga-ui/**',  // <-- transform all `@taiga-ui` sub-packages
],
},
```
=> fix(platform): add support for @ng-web-apis and @taiga-ui deps w/SSR

packages/create-analog/template-latest/src/app/pages/index.page.ts, packages/create-analog/template-minimal/src/app/pages/index.page.ts
https://github.com/analogjs/analog/issues/1351
Closes #1351
"Read the doc" link is visible in lightmode
=> fix(create-analog): read the doc color scheme in light mode

packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #1359
Removes the false positive during a Windows build where its unable to resolve `std-env` package. The error didn't have any impact on the running application.
=> fix(vite-plugin-nitro): inline std-env package for Windows build

packages/create-analog/__tests__/cli.spec.ts, packages/create-analog/files/analog-env.d.ts, packages/create-analog/files/styles.css, packages/create-analog/index.js, packages/create-analog/template-blog/src/app/app-root.ag, packages/create-analog/template-blog/src/app/app-root.spec.ts, packages/create-analog/template-blog/src/app/app.component.ts, packages/create-analog/template-blog/src/app/pages/blog/[slug].page.ag, packages/create-analog/template-blog/src/app/pages/blog/[slug].page.ts, packages/create-analog/template-blog/src/app/pages/blog/index.page.ag, packages/create-analog/template-blog/src/app/pages/blog/index.page.ts, packages/create-analog/template-blog/src/main.server.ts, packages/create-analog/template-blog/src/main.ts, packages/create-analog/template-blog/vite.config.ts, packages/create-analog/template-latest/src/app/app-root.ag, packages/create-analog/template-latest/src/app/app-root.spec.ts, packages/create-analog/template-latest/src/app/app.component.ts, packages/create-analog/template-latest/src/app/pages/index.page.ag, packages/create-analog/template-latest/src/app/pages/index.page.ts, packages/create-analog/template-latest/src/main.server.ts, packages/create-analog/template-latest/src/main.ts, packages/create-analog/template-latest/src/styles.css, packages/create-analog/template-latest/vite.config.ts, packages/create-analog/template-minimal/src/app/app-root.ag, packages/create-analog/template-minimal/src/app/pages/index.page.ag, packages/create-analog/template-minimal/src/app/pages/index.page.ts, packages/create-analog/template-minimal/src/main.server.ts, packages/create-analog/template-minimal/src/main.ts, packages/create-analog/template-minimal/vite.config.ts
Closes #1369
When creating a new Analog app (latest/blog/minimal) there is an option to select Analog SFC as a preferred component authoring format. When selected, all components and pages in a created project will be Analog SFCs.
=> feat(create-analog): optionally generate new projects with Analog SFCs

packages/router/src/lib/cookie-interceptor.ts, packages/router/src/lib/request-context.ts
Closes #1383
When prerendering pages that use server-side data fetching, get the initial request from the transfer state to prevent data fetching on the initial page load.
=> fix(router): retrieve initial server page load from transfer state

apps/analog-app/src/app/pages/form-action.directive.ts, packages/router/src/index.ts, packages/router/src/lib/inject-route-endpoint-url.ts, packages/router/src/lib/provide-file-router.ts, packages/router/src/lib/route-config.ts
Closes #
Exposes the `injectRouteEndpointURL` function to get the page endpoint for a given page. Meant to be used to the form action directive and will not remain public.
=> fix(router): expose inject function for page endpoint URL

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vite-plugin-angular/src/lib/angular-vitest-plugin.ts
Closes #1211
Closes #1212
When running tests
- esbuild is disabled eagerly for Vitest.
- esbuild is used in postprocessing the files that have gone through Angular compilation to realign the sourcemaps.
- IDE breakpoints work correctly.
- Coverage reports are accurate.
=> fix(vite-plugin-angular): use esbuild to postprocess sourcemaps during testing

packages/platform/src/lib/content-plugin.ts
Closes #
The `prism`, `marked`, and `marked-highlight` dependencies aren't loaded until a content file request is made.
=> fix(platform): load content highlighter on first content request

packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #
Applies the `ssrBuildDir` option when building the server
=> fix(vite-plugin-nitro): use ssrBuildDir if provided for SSR entry point

packages/router/src/lib/route-config.ts
Closes #
HttpClient is not injected if page endpoints are not configured
=> fix(router): inject HttpClient only when page endpoint is configured

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Fixes #1394 
Fixes #1345
In some cases, when adding or renaming page route files, the dev server had to be restarted, along with hard refreshing the browser for the changes to be picked up. 
This fix forces a rebuild/re-analysis of the Angular compilation with the newly added/renamed files, so renaming a page route file is picked up and refreshed correctly without restarting.
=> fix(vite-plugin-angular): force rebuild and analysis on file changes

packages/vite-plugin-angular/src/lib/angular-build-optimizer-plugin.ts
Closes #
`ngDevMode` is applied to the `define` object so dev-mode only code is tree-shaken in production
=> fix(vite-plugin-angular): set ngDevMode in during build optimization

apps/docs-app/docs/features/api/websockets.md, apps/docs-app/sidebars.js, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #1398 
* Enables WebSocket support for development environment
* Adds WebSocket documentation
=> fix(vite-plugin-nitro): enable websocket support & add docs

packages/vite-plugin-angular/src/lib/angular-build-optimizer-plugin.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #
Fixes an issue potentially in Nx 20 where NODE_ENV is no longer set to `production` because of a change in the `@nx/vite` package on how the Vite config is loaded. Now the `production` flag is inferred from the `mode` in the vite config during the build.
=> fix(vite-plugin-angular): infer production build from config mode instead of NODE_ENV

packages/vite-plugin-angular/src/lib/angular-build-optimizer-plugin.ts
Closes #
Angular v19 introduces a new `ngServerMode` variable that is used internally to tree-shake framework server code. This allows the Vite plugin to mimic the same behavior.
=> fix(vite-plugin-angular): add define option for ngServerMode

packages/vite-plugin-angular/src/lib/angular-build-optimizer-plugin.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Related to: https://github.com/storybookjs/storybook/issues/22544#issuecomment-2455088246
`process.env['NODE_ENV'] === 'production'` is used as a fallback check for production mode so the correct flags are set for prod optimizations and tree-shaking.
=> fix(vite-plugin-angular): add NODE_ENV check as fallback for production

packages/platform/src/lib/deps-plugin.ts
Closes #
Adds `nx` to the `optimizeDependencies.exclude` array to prevent it from being optimized through esbuild.
=> fix(platform): exclude Nx package from Vite optimizations

packages/vitest-angular/package.json, packages/vitest-angular/tsconfig.json
Closes #1436 
Closes #1437
- Sets the `type` is set to `commonjs` for the `vitest-angular` package to be fully compatible with Angular builders and native Vitest.
- Fixes console warning about sourcemaps
=> fix(vitest-angular): set correct type in package.json based on output format

apps/analog-app/project.json, libs/card/project.json, packages/vite-plugin-angular/src/lib/angular-vitest-plugin.ts
Closes #1440 
Angular Material and using Material Harnesses for testing is supported without additional vite configuration. 
- The `@angular/material` package wasn't being transformed when only using the `@analogjs/vite-plugin-angular` package.
- The `@angular/cdk/testing/testbed` package as not being properly optimized for testing with zone.js
- Also fixed a bug where inline styles were being processed by the internal sourcemap plugin.
=> fix(vite-plugin-angular): improve support for Angular Material and testing using harnesses

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
The current plugin creates a new compiler for each test file, thus slowing down tests.
P.S.: I am willing to add some performance tests but let's discuss the strategy first 😊
This PR speeds up tests considerably (3x to 10x)
=> perf(vite-plugin-angular): speed up tests by reusing compiler

apps/analog-app/src/app/about.ts, apps/analog-app/src/app/app.config.ts, apps/docs-app/docs/features/routing/overview.md, packages/router/src/index.ts, packages/router/src/lib/provide-file-router.ts, packages/router/src/lib/routes.ts
Closes #
The `withExtraRoutes` function is made public to allow existing Angular routes to be provided in addition to the filesystem-based routes array that is crawled and built.
=> fix(router): make withExtraRoutes function public

package.json, packages/platform/package.json, packages/vite-plugin-nitro/package.json, packages/vite-plugin-nitro/src/lib/vite-nitro-plugin.spec.data.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts, pnpm-lock.yaml
Closes #1448
Nitro is updated to `2.10.x` and a default `compatbilityDate` is added to remove console warnings.
Nitro 2.10.0 release notes: https://github.com/nitrojs/nitro/releases/tag/v2.10.0
=> feat(vite-plugin-nitro): update Nitro to 2.10.x and add default compatibility date

apps/analog-app/vite.config.ts, packages/router/src/lib/request-context.ts
Closes #1421
HttpClient requests for static assets are handled correctly during prerendering with transfer state.
For example, a public asset may be stored in `public/assets/shipping.json` and referenced as `http.get('/assets/shipping.json')`. The asset will be cached/transferred correctly with no double request on initial load.
=> fix(router): support transfer state/prerendering for static assets

packages/platform/src/lib/deps-plugin.ts
Closes #
- Adds `@nx/module-federation` and `@nx/rspack` to be excluded from esbuild optimization
=> fix(platform): exclude Nx Module Federation package from optimization

packages/create-analog/template-blog/package.json, packages/create-analog/template-latest/package.json, packages/create-analog/template-minimal/package.json
Closes #
- Adds temporary npm overrides to support installation without peer dependency errors until Nx 20.2 is released with support for Angular v19.
=> fix(create-analog): add npm overrides for @nx/angular

packages/vite-plugin-angular/src/lib/angular-vitest-plugin.ts
Reproduction: https://github.com/zargham-leanix/vitest-fake-async
Closes # https://github.com/testing-library/angular-testing-library/issues/505
Allows `@testing-library/angular` to be used out of the box with `fakeAsync` tests without errors. The packages need to be downleveled from async/await in order to support `zone.js` and `fakeAsync`.
=> fix(vite-plugin-angular): add inline deps for angular testing library

packages/create-analog/template-blog/angular.json, packages/create-analog/template-latest/angular.json, packages/create-analog/template-minimal/angular.json
Remove useless property on angular.json templates
Closes #1474 
Generate angular.json without root property
=> fix(create-analog): set root property to empty on angular.json

.github/workflows/test-release.yml, packages/create-analog/template-blog/package.json, packages/create-analog/template-latest/package.json, packages/create-analog/template-minimal/package.json
Closes #
Nx 20.2 is released with support for Angular v19 in the `@nx/angular` package.
=> fix(create-analog): remove override for @nx/angular package

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #1288
In JIT mode, files already transformed containing external styles and template are excluded from being re-transformed in case the plugin is included multiple times through a combination of tools like Vitest and Storybook.
=> fix(vite-plugin-angular): skip double transform in JIT mode

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #
Instead of returning the id, return undefined to let the resolveId pass through
=> fix(vite-plugin-angular): return undefined when not resolving id

packages/vite-plugin-angular/src/lib/angular-vitest-plugin.ts
Closes #1488 
When apply the sourcemap transform during testing, only apply the transform to TypeScript files.
=> fix(vite-plugin-angular): only apply sourcemap transform to TS files

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #1501 
When watch mode is enabled during testing, each file is re-transformed individually to make sure changes within tests are updated.
=> fix(vite-plugin-angular): properly transform files during watch mode

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vitest-angular/src/lib/builders/test/vitest.impl.ts
Closes #1507
Adds additional checks for watch mode during testing.
=> fix(vitest-angular): set watch mode flag when passed from CLI args

libs/card/project.json, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vitest-angular/src/lib/builders/test/vitest.impl.ts
Related to #1507 
Use the vite overrides through Vitest to set the `test.watch` flag for detecting watch mode.
=> fix(vitest-angular): use vite overrides to pass test watch mode

packages/platform/src/lib/deps-plugin.ts
Closes #
- Adds the `front-matter` package to the default group of optimized packages for content-based applications
=> fix(platform): add front-matter for default optimization

apps/analog-app/src/app/app.config.server.ts, apps/analog-app/src/app/pages/client/(client).page.ts, apps/analog-app/src/app/pages/goodbye.page.analog, apps/analog-app/src/app/pages/server/(server).page.ts, apps/analog-app/src/main.server.ts, apps/analog-app/src/server/components/goodbye.ag, apps/analog-app/src/server/components/hello.ts, apps/analog-app/tsconfig.app.json, apps/analog-app/vite.config.ts, apps/blog-app/src/main.server.ts, apps/trpc-app/src/main.server.ts, packages/create-analog/template-blog/src/main.server.ts, packages/create-analog/template-latest/src/main.server.ts, packages/create-analog/template-minimal/src/main.server.ts, packages/nx-plugin/src/generators/app/files/template-angular-v18/src/main.server.ts__template__, packages/platform/src/lib/deps-plugin.ts, packages/platform/src/lib/router-plugin.ts, packages/router/server/src/index.ts, packages/router/server/src/render.ts, packages/router/server/src/server-component-render.ts, packages/router/server/src/tokens.ts, packages/router/src/index.ts, packages/router/src/lib/cache-key.ts, packages/router/src/lib/request-context.ts, packages/router/src/lib/server.component.ts
Closes #989 
Introduces `Analog Server Components` which are inspired by/similar to `Nuxt Server Components` and `Astro Islands` in that the component is **only** rendered on the server, with its HTML output being sent back to the client. 
This is not the same as Incremental Hydration in Angular, where the client-side JS is loaded for the component(s) after the hydration trigger happens. The JS for these components is _never_ sent to the client.
- NOTES
- No client-side interactivity: Rendered links will cause a page to reload upon clicking. We do have a directive that can be used to intercept these clicks and perform navigation, but that's not part of this initial effort. These components render heavy HTML content on the server without sending the JavaScript to the client.
- Angular …
=> feat(router): introduce support for Analog Server Components

packages/vitest-angular/src/lib/builders/build/vitest.impl.ts, packages/vitest-angular/src/lib/builders/test/vitest.impl.ts
Closes #
The `build-test` executor was respawning a new server on each change in watch mode. Now it will reuse the same Vitest server to run the tests after changes are made.
=> fix(vitest-angular): reuse vitest server in watch mode for build-test

packages/vitest-angular/src/lib/builders/test/schema.d.ts, packages/vitest-angular/src/lib/builders/test/schema.json, packages/vitest-angular/src/lib/builders/test/vitest.impl.ts
Closes #1520 
This PR adds support for the `--coverage` and `--ui` flags in the `@analogjs/vitest-angular` builder CLI. Users can now dynamically enable these options without manually configuring them in `angular.json`.
Example usage:
```bash
ng test --coverage   # Display test coverage  
ng test --ui         # Enable UI mode  
```
This simplifies testing workflows by reducing unnecessary `angular.json` complexity.
=> feat(vitest-angular): add UI and coverage options to test

apps/analog-app/vite.config.ts, apps/ng-app/vite.config.ts, packages/platform/src/lib/options.ts, packages/platform/src/lib/platform-plugin.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vite-plugin-angular/src/lib/utils/hmr-candidates.ts
Closes #1524
When using the `liveReload` option in the `analog` plugin with Angular v19, the new HMR code generated by the compiler is handled by the vite plugin, enabling HMR updates without full page reloads.
- Inline styles and templates are supported
- External styles and templates are supported
- Page reloads occur when classes are changed (logic copied from Angular compilation)
```ts
// ..other config
plugins: [analog({ liveReload: true })],
}));
```
Links
https://vite.dev/guide/api-plugin.html#handlehotupdate
https://bjornlu.com/blog/hot-module-replacement-is-easy#importmetahotaccept
=> feat(vite-plugin-angular): introduce support for Angular v19 HMR/live reload

apps/docs-app/docs/features/deployment/providers.md, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #1528
- Adds zero-config support for deploying fullstack Analog applications to Firebase App Hosting. No `preset` is necessary, as the default is `node-server` which is what Firebase App Hosting needs. 
- Updates docs with Firebase App Hosting section.
- Adds note about Zerops as deployment partner.
=> feat(vite-plugin-nitro): add support for Firebase App Hosting deployment

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #
When running tests in watch mode, the test files won't be re-compiled until they are invalidated. This increases the speed for the initial test run because files have not been changed since the first build
=> fix(vite-plugin-angular): skip rebuilds before invalidation during testing

libs/card/vite.config.ts, package.json
Closes #
- Skips nx caching when running Vite Ecosystem CI tests
- Changes `pool` for `card` tests to workaround segfault with node 22+
=> ci: skip caching for Vite tests, fix segfault with node 22 for card tests

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #1534
HMR of component styles works when using an NgModule bootstrapped application or when animations are enabled
Found by looking at the angular CLI source:
https://github.com/angular/angular-cli/blob/9b57ff0552736e6fef44c0ff7e6535f9ed832c6b/packages/angular/build/src/builders/dev-server/vite-server.ts#L142-L143
https://github.com/angular/angular-cli/blob/9b57ff0552736e6fef44c0ff7e6535f9ed832c6b/packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts#L707
=> fix(vite-plugin-angular): fix HMR of component styles

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #1532
Fixes typechecking of .ts files (implementation [borrowed from the angular CLI](https://github.com/angular/angular-cli/blob/9b57ff0552736e6fef44c0ff7e6535f9ed832c6b/packages/angular/build/src/tools/angular/compilation/aot-compilation.ts#L246-L264)). Currently only component templates are typechecked. 
As this has the potential to impact performance, we also add a `disableTypeChecking` option to disable typechecking completely (so that folks can run `ngc --noEmit` to typecheck separately)
=> feat(vite-plugin-angular): fix .ts typechecking and add disableTypeChecking option

libs/card/vite.config.ts
Closes #
When running `card` tests in parallel with node22+ and `vmForks` an error is thrown. This disables file parallelism for the card library to stabilize the tests in CI.
=> ci: disable file parallelism for card lib

.gitignore, apps/analog-app/vite.config.ts, package.json, packages/platform/src/lib/deps-plugin.ts, pnpm-lock.yaml
Closes #
When using the `@analogjs/platform` plugin, TypeScript files are excluded from being transpiled by esbuild during the build. This is handled by the Angular compiler and is a bit of unnecessary overhead.
esbuild is already disabled during development.
Before:
After:
=> perf(platform): exclude TypeScript files from Vite esbuild plugin

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vite-plugin-angular/src/lib/host.ts
Follow up to https://github.com/analogjs/analog/pull/1539
In https://github.com/analogjs/analog/pull/1539 I thought I had fixed HMR, but actually what that change did was disable HMR for component stylesheets and trigger a full reload 🤦‍♂️ 
So this followup implements the missing pieces:
1. Implements the appropriate callback for component stylesheets in the `handleHotUpdate` plugin hook to reimplement HMR of component styles
2. Handles `ViewEncapsulation.Emulated` components by using the `encapsulateStyle` helper
Relevant bits from the CLI where I based this code from:
* https://github.com/clydin/angular-cli/blob/602081d18f3c5e0a878f4bf0986461d8b6041130/packages/angular/build/src/builders/dev-server/vite-server.ts#L479-L514
* https://github.com/angular/angular-cli/blob/ddae37fdf3c1c93bd2a …
=> fix(vite-plugin-angular): correctly implement HMR of component styles

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, packages/vite-plugin-angular/src/lib/host.ts
Closes #
Fixes HMR of component `styleUrls` when using SSG. Without this patch, all component stylesheet urls will be added to the DOM twice, and only the first one will be reloaded dynamically so the changes won't appear on the page.
To test it locally, you can make a change in `apps/analog-app/src/app/pages/shipping/shipping.scss` and observe HMR working on `http://localhost:3000/shipping`
=> fix(vite-plugin-angular): fix SSG and HMR of external component stylesheets

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #
- Only store valid HMR updates from the compiler. 
- Correctly clears cache of HMR updates when full page reload is triggered, presenting app rendering inconsistencies.
=> fix(vite-plugin-angular): only store valid HMR updates and clear on a full page reload

packages/platform/src/lib/options.ts, packages/platform/src/lib/platform-plugin.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #1551 
- Type checking diagnostics were added and enabled by default, which could break existing apps. The type checking is disabled in the plugin by default, and enabled in the platform plugin for apps.
=> fix(vite-plugin-angular): disable type checking diagnostics by default

packages/vite-plugin-angular/src/lib/angular-pending-tasks.plugin.ts
Closes #1554
The whole angular version is used to determine whether its earlier than version 19.0.4 when doing the replacement for the PendingTasks symbol.
=> fix(vite-plugin-angular): use whole angular version for pending tasks replacement

packages/platform/src/lib/deps-plugin.ts
Vite showed the following error because the @tanstack-angular-experimental was not in the known dep list. 
Closes #
Serving analog project no longer shows RuntimeError for any injection from the @tanstack-angular-experimental library.
=> added angular-query to the internal deps list

packages/nx-plugin/src/generators/app/files/trpc/src/server/trpc/trpc.ts__template__, packages/nx-plugin/src/generators/app/files/trpc/src/trpc-client.ts__template__
Closes #1559
Data types like Date are supported, so if you have interface/types with Date, the response from tRPC will preserve the type and not change it to string.
=> fix(nx-plugin): add SuperJSON transformer to the tRPC template

packages/nx-plugin/src/generators/app/versions/dependencies.ts, packages/nx-plugin/src/utils/versions/dev-dependencies.ts, packages/nx-plugin/src/utils/versions/ng_19_X/versions.ts
Closes #1565
- When using the Analog Nx preset or generating a new application, the latest `@angular/platform-server` version is installed.
- Vite is installed as a dev dependency.
=> fix(nx-plugin): ensure correct installation of Angular/Vite packages

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #1564 
Diagnostic error messages from compilation are correctly displayed when full type checking is enabled.
=> fix(vite-plugin-angular): unwrap typechecking diagnostic messages

packages/vite-plugin-angular/src/lib/authoring/markdown-transform.ts
`defaultMarkdownTemplateTransform` was creating a new instance of `MarkedSetupService` each time the function ran. For a site with ~150 content files, this led to a wait time of ~10 mins per change for the page to update. The server would also sometimes crash with an out of memory error.
The `MarkedSetupService` is just created once, which brings the time for ~150 content files down to ~10 seconds.
=> fix(vite-plugin-angular): cache MarkedSetupService creation

packages/vite-plugin-angular/src/lib/authoring/analog.spec.ts, packages/vite-plugin-angular/src/lib/authoring/analog.ts
While using SFCs I had issues with the import attributes only supporting single quotes. I installed Analog in my NX mono repo and eslint is configured for double quotes.
I spent a couple of hours figuring out it was the quote not parsed correctly in the Analog file processor.
Maybe it's deliberate and I'm the only one in this space using double quotes, but I think double quotes should be supported regarding the spec for import attributes.
Also updated the test case.
I'm not sure that the implementation does cover any edge cases or should cover any other edge cases, any advice on this ?
Double and single are supported in the same way for import attributes.
=> fix(vite-plugin-angular): support double quotes in analog import attributes

apps/blog-app/vite.config.ts, packages/vite-plugin-angular/src/lib/host.ts
The fix for stylesheets introduced in this PR: https://github.com/analogjs/analog/pull/1548 was affecting `agx` file reads, causing this error when using `liveReload`:
```
Error: Unable to locate component resource: ad4a60f31e46cd89ca8510889c7b9419076f239c2fb9738980044ba80e354986.agx
```
This PR adds an exception for `.agx` files so the filenames are not hashed
=> fix(vite-plugin-angular): add exception for agx to resourceNameToFileName

packages/vite-plugin-angular/src/lib/host.ts
Same issue as https://github.com/analogjs/analog/pull/1595 but it is also happening for `.ag` (and I assume `.analog`) files
Instead of checking for all valid exceptions, `resourceNameToFileName` will just check for style extensions (`.css` and `.scss`)
=> fix(vite-plugin-angular): check for style extension in resourceNameToFileName

packages/vite-plugin-angular/src/lib/angular-vite-plugin.spec.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #1598 
When using the Vitest CLI directly, watch mode is picked up correctly.
=> fix(vite-plugin-angular): add detection for Vitest CLI in watch mode

packages/vitest-angular/package.json
Closes #1609 
Expand version range of @angular-devkit/architect to include 0.1901.x
=> fix(vitest-angular): expand semver range of @angular-devkit/architect

.all-contributorsrc, package.json, packages/vite-plugin-nitro/src/lib/build-sitemap.ts, packages/vite-plugin-nitro/src/lib/plugins/dev-server-plugin.ts, packages/vite-plugin-nitro/src/lib/vite-nitro-plugin.spec.data.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.spec.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #
This adds support for Vite's Environment API, with a fallback to the previous build behavior if the build is not initiated through the Environment API. This keeps backward compatibility for Vite 5 and if the Nx Vite executor is still being used.
In the future support for the legacy build setup can be removed.
=> feat(vite-plugin-nitro): implement support for Vite Environment API

packages/vitest-angular/src/lib/builders/test/schema.d.ts, packages/vitest-angular/src/lib/builders/test/schema.json, packages/vitest-angular/src/lib/builders/test/vitest.impl.ts
Closes #1549
This PR adds an update option to `@analogjs/vitest-angular:test` builder, enabling snapshot updates during testing.
Changes:
- Added the `update` option to schema.json with an alias `u`, allowing users to update snapshots.
- Updated the vitestBuilder function to integrate the update option into the test configuration.
=> feat(vitest-angular): add support for snapshot updates in test builder

.all-contributorsrc, package.json, packages/create-analog/template-blog/package.json, packages/create-analog/template-blog/tsconfig.json, packages/create-analog/template-latest/package.json, packages/create-analog/template-latest/tsconfig.json, packages/create-analog/template-minimal/package.json, packages/create-analog/template-minimal/tsconfig.json, packages/platform/package.json, pnpm-lock.yaml
Closes #
- Vite/Vitest overrides have been removed from the templates
- The `vitefu` package is updated to 1.x to support Vite 6
- tsconfig moduleResolution updated to `bundler`
- TypeScript default updated to 5.8
=> fix(create-analog): remove overrides from templates for Vite/Vitest

package.json, packages/vite-plugin-nitro/package.json, pnpm-lock.yaml
Closes #1617 
Bumps `esbuild` dependency to `0.25.0` to mitigate vulnerabilities from older versions.
=> fix(vite-plugin-nitro): bump esbuild dependency to 0.25.0

packages/nx-plugin/src/generators/init/lib/update-test-tsconfig.ts, packages/nx-plugin/src/generators/setup-vitest/lib/update-tsconfig.ts
Closes #1645 
When running the schematic to setup Vitest or migrate to Analog w/Vitest, the `files` array in the `tsconfig.spec.json` is set to the new `src/test-setup.ts` file.
=> fix(nx-plugin): overwrite files array when setting up Vitest

apps/blog-app/vite.config.ts, apps/docs-app/docs/features/server/static-site-generation.md, packages/platform/src/lib/options.ts, packages/vite-plugin-nitro/src/index.ts, packages/vite-plugin-nitro/src/lib/build-sitemap.ts, packages/vite-plugin-nitro/src/lib/options.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #1525
Closes #1599 
The `prerender.routes` array can include an object that defines the `route` and `sitemap` properties for customizing the sitemap definition for the prerendered route.
```ts
import fs from 'node:fs';
plugins: [
analog({
prerender: {
sitemap: {
host: 'https://analogjs.org/',
},
routes: async () => [
'/',
'/blog',
{
route: '/blog/2022-12-27-my-first-post',
sitemap: {
lastmod: '2022-12-27',
},
},
{
contentDir: '/src/content/archived',
transform: (file: PrerenderContentFile) => {
return `/archived/${file.attributes.slug || file.name}`;
},
sitemap: (file: PrerenderContentFile) => {
return {
lastmod: 'read last …
```
=> feat(vite-plugin-nitro): allow customization of sitemap definition for prerendered routes

packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #
Public assets were being bundled into the server build through the `nitro.serverAssets` build option, but were never exposed through storage. This removes server assets from the build process, decreasing the bundle size and overall build time. The public assets are still served when static file servers such as node are used.
analog-app build before was 4.77MB 1.1MB gzipped, and is now 3.1MB 685kb gzipped.
This should decrease memory usage also as the files are no longer bundled.
=> perf(vite-plugin-nitro): remove server assets from build process

packages/vite-plugin-angular/src/lib/angular-storybook-plugin.ts
Updates angular-storybook-plugin to work with the new package.json exports introduced in @storybook/angular v8.6.9
Closes #1657
None
=> fix(vite-plugin-angular): update angular-storybook-plugin with @storybook/angular v8.6.8+

.prettierignore, packages/vite-plugin-nitro/src/lib/vite-nitro-plugin.spec.data.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #
The internal `autoImports` flag is disabled, as we do not expose auto-imports by default. This also helps with compatibility when using Rolldown with Vite. 
To enable manually:
```ts
build: {
target: ['es2020']
},
resolve: {
mainFields: ['module'],
},
plugins: [
analog({
nitro: {
imports: {
autoImport: true
},        
}
})
],
test: {
globals: true,
environment: 'jsdom',
setupFiles: ['src/test-setup.ts'],
include: ['**/*.spec.ts'],
reporters: ['default'],
},
define: {
'import.meta.vitest': mode !== 'production',
},
}));
```
=> fix(vite-plugin-nitro): disable internal autoImports by default

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
When trying to build with `"complationMode": "partial"` set in `tsconfig.json`, the following errors occur:
```
vite v6.2.5 building for production...
✓ 0 modules transformed.
✗ Build failed in 1.19s
error during build:
[@analogjs/vite-plugin-angular] TestBed support ("supportTestBed" option) cannot be disabled in partial compilation mode.
at NgCompiler.makeCompilation (file:///Users/.../node_modules/@angular/compiler-cli/bundles/chunk-UJU2GLGZ.js:4224:13)
at file:///Users/.../node_modules/@angular/compiler-cli/bundles/chunk-UJU2GLGZ.js:3838:31
at ActivePerfRecorder.inPhase (file:///Users/.../node_modules/@angular/compiler-cli/bundles/chunk-Q2WE7ECN.js:142:14)
at NgCompiler.analyzeAsync (file:///Users/.../node_modules/@angular/compiler-cli/bundles/chunk-UJU2GLGZ.js:3837:29)
at …
```
=> fix(vite-plugin-angular): reenables test bed and jit mode for partial compilations

packages/vite-plugin-nitro/README.md, packages/vite-plugin-nitro/src/lib/build-ssr.ts, packages/vite-plugin-nitro/src/lib/options.ts, packages/vite-plugin-nitro/src/lib/plugins/dev-server-plugin.ts, packages/vite-plugin-nitro/src/lib/utils/get-page-handlers.ts, packages/vite-plugin-nitro/src/lib/utils/register-dev-middleware.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #1672 
- By default, the Nitro plugin looks at the `src` directory for server API routes. This adds the `sourceRoot` option to make this configurable to a different directory, or optional by setting it to `.`.
- Added docs for the new option.
- Fixes a bug where it throws an error when using `vite build` with SSR disabled and no server entry file setup, as it still tried to build the ssr environment.
=> feat(vite-plugin-nitro): make source root configurable/optional

apps/docs-app/docs/features/server/server-side-rendering.md, packages/vite-plugin-nitro/src/lib/build-server.ts
Closes #1686
Closes #1687
- If `ssr` is enabled, and the prerender routes array is empty, the root `index.html` is removed from the built static assets. This allows SSR to be used as the default for all requests.
- Docs have been updated on opting-out of prerendering.
Previously, the root `index.html` would still be included from the client build even if the routes array was empty with `ssr` enabled. The default behavior still prerenders the `/` route.
=> fix(vite-plugin-nitro): fix behavior when opting out of prerendering

nx.json
This PR removes the two outdated overrides for the Nx task runner:
- light client - This flag was used during the transition to the light client and is only applicable when used with an explicitly installed `nx-cloud` client npm package. In modern Nx CLI, the nx-cloud client is automatically downloaded/updated from the API and is always a `light` client.
- legacy cache - From v21 there will no longer be legacy cache. This flag made sense during the early days of new database caching when there were some instabilities. It's now safe to use the new, faster caching logic.
Closes #
The behavior should remain the same, with Nx caching being slightly faster and future-proof.
=> ci: remove legacy nx-cloud overrides

packages/vite-plugin-nitro/src/lib/build-server.ts
Closes #1360
When all prerendering is disabled, remove the compressed root index.html(.br|.gz) from the public assets.
=> fix(vite-plugin-nitro): remove compressed index files for SSR-only rendering

apps/docs-app/docs/features/routing/middleware.md, packages/nx-plugin/src/generators/app/files/template-angular-v18/tsconfig.app.json__template__, packages/nx-plugin/src/generators/app/files/template-angular-v19/tsconfig.app.json__template__, packages/nx-plugin/src/generators/init/lib/update-app-tsconfig.ts
Closes #1633 
- When generating new applications with Nx, the middleware include is added to the tsconfig.app.json.
- When migrating an existing application, the middleware include is added to the tsconfig.app.json.
- The docs have been updated for existing apps without the middleware include, and using environment variables.
=> fix(nx-plugin): add middleware include to app templates, update docs

packages/platform/src/lib/content/marked/index.ts, packages/platform/src/lib/content/marked/marked-setup.service.ts
Closes #
The platform plugin for content accepts an array of extensions that can be passed to marked for markdown rendering.
=> feat(content): add ability to pass extensions to marked instance

packages/platform/src/lib/content/marked/marked-setup.service.ts
Currently, Analog's content pipeline instantiates a Marked Renderer and a Parser to add custom formatting for code, codespan, and paragraph tokens. Unfortunately, this means that new Marked extensions can't decorate the Renderer or Parser with new tokens. 
Refactors the handling of these tokens into a MarkedExtension, letting this wrapping happen as part of Marked's extension flow.
=> fix(platform): allow marked extensions to add new renderers

packages/vite-plugin-angular/package.json, packages/vite-plugin-angular/project.json
Closes #
When using the `@analogjs/storybook-angular` package to a Storybook project in an Nx workspace, it fails to import the package when used with `require` internally because the generated `package.json` exports does not list `require`. The package manager was `pnpm`.
=> fix(vite-plugin-angular): allow the plugin to be imported with commonjs/require

packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #
When an `apiPrefix` is used, it should match the API route defined in that directory.
Example: An `apiPrefix` of `services` should contain API routes in the `src/server/routes/services` directory.
=> fix(vite-plugin-nitro): check for custom apiPrefix with api directory

apps/docs-app/docs/integrations/angular-material/index.md
Closes #1631 
Added instructions on using legacy sass compiler API when using Angular Material.
importing `zone.js/node` causes issues with the modern sass compiler API due to `zone.js` patching the global `Promise` used inside the `sass-embedded` package. 
Issue filed in Angular repo: https://github.com/angular/angular/issues/61090
=> docs: update setup guide for Angular Material w/note on zone.js

.github/ISSUE_TEMPLATE/01-bug-report.yml, .github/ISSUE_TEMPLATE/02-feature-request.yml
Closes #
Adds `storybook-angular` as an option to the bug reporting and feature request GitHub issue templates
=> chore: add storybook-angular option to github issue templates

apps/analog-app/src/app/pages/package.page.ts, apps/docs-app/docs/guides/libraries.md, apps/docs-app/sidebars.js, libs/my-package/.eslintrc.json, libs/my-package/README.md, libs/my-package/package.json, libs/my-package/project.json, libs/my-package/src/index.ts, libs/my-package/src/lib/my-package/my-package.component.html, libs/my-package/src/lib/my-package/my-package.component.spec.ts, libs/my-package/src/lib/my-package/my-package.component.ts, libs/my-package/src/test-setup.ts, libs/my-package/tsconfig.json, libs/my-package/tsconfig.lib.json, libs/my-package/tsconfig.lib.prod.json, libs/my-package/tsconfig.spec.json, libs/my-package/vite.config.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts, tsconfig.base.json, vitest.workspace.ts
Closes #
Improves support for building Angular libraries using Vite:
- Infers correct `tsconfig.lib.json` / `tsconfig.lib.prod.json` for libraries
- Infers correct tsconfig based on app/test/library environment
- Adds a sample `my-package` library for validation
- Adds a guide for building a library using Vite
=> fix(vite-plugin-angular): improve support for building Angular libraries

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #
When building declaration files for a library, the types are not nested within the `src` folder.
=> fix(vite-plugin-angular): adjust output path for library dts files

packages/vite-plugin-angular/src/lib/angular-pending-tasks.plugin.ts
Closes #1730
The minor and major versions are normalized to two digits before combining when doing a version check for older Angular versions.
=> fix(vite-plugin-angular): normalize version string for pending tasks replacement

packages/create-analog/index.js, packages/create-analog/template-blog/vite.config.ts, packages/create-analog/template-latest/vite.config.ts, packages/create-analog/template-minimal/vite.config.ts
Closes #1732 
- Updated `marked` dependency to latest version with `shiki` highlighter
- Correctly adds Tailwind to vite config when selected
- Updates to Nx 21
=> fix(create-analog): use latest version of marked w/shiki, fix tailwind support

apps/docs-app/docs/contributors.mdx, apps/docs-app/docs/experimental/sfc/index.md, apps/docs-app/docs/getting-started.md, apps/docs-app/docs/integrations/nx/index.md, apps/docs-app/docusaurus.config.js
Closes #
- A `llms.txt` and `llms-full.txt` is generated from the documentation files for consumption by LLMs.
- Updated titles for some docs pages.
Credit to Prisma docs: https://github.com/facebook/docusaurus/issues/10899
=> docs: add plugin support to generate llms.txt from documentation

packages/vitest-angular/package.json
The `@analogjs/vitest-angular` has a peer dependency range for `@angular-devkit/architect` that doesn't include its v20 version.
Closes #
The `@analogjs/vitest-angular` supports `@angular-devkit/architect@20`.
=> fix(vitest-angular): update `@angular-devkit/architect` dep range to include v20

apps/analog-app/vite.config.ts, apps/docs-app/docs/features/server/static-site-generation.md, apps/docs-app/i18n/de/docusaurus-plugin-content-docs/current/features/server/static-site-generation.md, apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current/features/server/static-site-generation.md, apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/server/static-site-generation.md, apps/trpc-app/vite.config.ts, packages/nx-plugin/src/generators/app/files/template-angular-v15/vite.config.ts__template__, packages/nx-plugin/src/generators/app/files/template-angular-v16/vite.config.ts__template__, packages/nx-plugin/src/generators/app/files/template-angular-v17/vite.config.ts__template__, packages/nx-plugin/src/generators/app/files/template-angular-v18/vite.config.ts__template__
Closes #
The `splitVendorChunkPlugin` has been removed in Vite 7. This is just cleanup from our docs and samples.
=> chore: remove occurrences of splitVendorChunkPlugin from vite

packages/astro-angular/README.md
Closes #
It is a very tiny addition
When I first saw `static renderProviders = [];` I didn't copy it because I didn't see the point of copying an empty array.
Later on I looked up another project and saw how it's used and I believe that including that in the docs would make it easier for others that are also exploring the integration
=> docs(astro-angular): add providers to example

apps/analog-app/vite.config.ts, apps/docs-app/docs/features/server/static-site-generation.md, packages/vite-plugin-nitro/src/lib/options.ts, packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
Closes #1762 
When using [Server-Side Data Fetching](https://analogjs.org/docs/features/data-fetching/server-side-data-fetching), the data is cached and reused using transfer state _only_ on the first request. To prerender the server-side data fetched along with the route, set the `staticData` flag to `true` in the config object for the prerendered route.
For example, a route defined as `src/app/pages/shipping.page.ts` with an associated `src/app/pages/shipping.server.ts` has the route and server data prerendered to be completely static.
```ts
plugins: [
analog({
static: true,
prerender: {
routes: async () => [
'/',
{ 
route: '/shipping', …
```
=> feat(vite-plugin-nitro): support static server side data fetching during prerendering

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #1733
When updating external templates/styles, compilation is triggered and files are updated correctly.
=> fix(vite-plugin-angular): trigger compilation from external templates/styles

packages/storybook-angular/preset/preset.mjs, packages/storybook-angular/src/types.ts
Closes #
When using the `@analogjs/storybook-angular` package in combination with a `vite.config.mts` file that is used for testing, the Analog plugin gets loaded twice with different settings, causing slowdowns in compilation. This filters out any analogjs plugins that were previously loaded before adding the plugin internally.
=> fix(storybook-angular): prevent duplicate loading of analogjs plugins

packages/vite-plugin-angular/src/lib/angular-storybook-plugin.ts, packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #1831 
The ESM import will be preferred with Storybook for newer versions.
=> fix(vite-plugin-angular): detect ESM import for storybook transform

packages/vite-plugin-angular/src/lib/component-resolvers.spec.ts, packages/vite-plugin-angular/src/lib/component-resolvers.ts
On Windows generated paths are `./app.component.css|C:/path/to/src/app.component.css` rather than `./app.component.css|/path/to/src/app.component.css`, causing tests to fail. Trying to understand where this issue is coming from, I found some older PRs (#275 and #799), that tried to utilize vite's `normalizePath()`, which [used to](https://github.com/vitejs/vite/commit/e2137b71a5a82580b2cf45e84ead136052014ac7#diff-071a32aedd2ea59472ebb69fb456e818b103d1a332da632e12c2d54395938ad1L63) also take care of Windows' drive letters, though that was ages ago.
Closes #1860
1) `./app.component.css|/path/to/src/app.component.css` now properly maps to `./app.component.css|/path/to/src/app.component.css`.
2) I changed the helper function into a proper matcher, making it easier in the future to see what …
=> test(vite-plugin-angular): fix path resolution for Windows

packages/storybook-angular/src/lib/builders.json, packages/storybook-angular/tsconfig.json, packages/storybook-angular/tsconfig.lib.json, packages/vite-plugin-angular-tools/builders.json, packages/vite-plugin-angular-tools/tsconfig.json, packages/vitest-angular/builders.json, packages/vitest-angular/tsconfig.json
Closes #
Angular CLI builders have support to be shipped as ESM, while schematics are still only supported with CommonJS. This updates the compilation configuration to `es2022` where applicable.
Nx executors are still built as CommonJS
=> feat: update Angular builders to compile to ESM

apps/blog-app/src/app/pages/archived/[slug].page.ts, apps/blog-app/src/app/pages/archived/index.page.ts, apps/blog-app/src/app/pages/blog/[slug].page.ts, apps/blog-app/src/app/pages/blog/index.page.ts, packages/content/resources/README.md, packages/content/resources/ng-package.json, packages/content/resources/src/content-file-resource.ts, packages/content/resources/src/content-files-resource.ts, packages/content/resources/src/index.ts, packages/content/src/index.ts, packages/content/src/lib/content-file-loader.ts, packages/content/src/lib/content-files-token.ts, packages/content/src/lib/content-list-loader.ts, packages/content/src/lib/inject-content-files.ts, packages/content/src/lib/provide-content.ts, tsconfig.base.json
Closes #1562 
Content loaders and resources are a signal-based way to load and consume content in Analog. They are also customizable to allow different async loaders to be used instead of the built-in default.
The two main APIs are the `contentFilesResource` that provides a list of content files with metadata, and the `contentFileResource` for retrieving an individual piece of content.
These are exposed as Angular resources under the `@analogjs/content/resources` entrypoint and do not change how the existing content APIs function.
The `blog-app` is also updated to use the content resource APIs.
=> feat(content): introduce content resources and loaders

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
Closes #1880 
The `resolve.conditions` in the vite plugin appends the provided conditions, or falls back to the `defaultClientConditions`. This allows node packages including MSW to be resolved correctly when running tests.
=> fix(vite-plugin-angular): use configured resolve conditions then defaults

packages/storybook-angular/preset/preset.mjs
Closes #1886 
When building the Storybook, esbuild no longer mangles the class names, which are needed by Compodoc to display API reference tables correctly.
=> fix(storybook-angular): don't mangle class names during the build
