package.json
packages/create-analog/project.json
yarn.lock

👋 I thought I would join the fun over here.
Closes #30

chore: resolve build on windows

---

.all-contributorsrc
README.md
package.json
yarn.lock

docs: add allcontributors for contributor acknowledgment

---

apps/docs-app/static/CNAME

chore(docs): add CNAME for analogjs.org to docs build

---

.github/ISSUE_TEMPLATE/01-bug-report.yml
.github/ISSUE_TEMPLATE/02-feature-request.yml

Add basic version of: 
- Bug issue template.
- Feature Request template.

chore(docs): add bug and feature request templates (#41)

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

Relates to #14 
Added the performance changes to the `@analogjs/vite-plugin-angular-optimizer` and `@analogjs/vite-plugin-angular` `transform` methods.

perf(vite-plugin-angular): add perf changes from esbuild browser builder

---

packages/create-analog/index.js

When the user does not use global git credentials, initialisation it will fail in a strange mode, with `execSync` output buffer in console. With the added try/catch only the stdout is showed
<details>
<summary>Before changes</summary>
```shell
❯ npm init analog
✔ Project name: … temp-analog
✔ Select a template: › Analog
✔ Select a variant: › angular-v14
Scaffolding project in /Users/iamandrewluca/Projects/iamandrewluca/temp-analog...
Initializing git repository:
Author identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: no email was given and auto-detection is disabled
Error: Command failed: …
```

fix(create-analog): fail silent when commit cannot be created

---

packages/astro-angular/README.md

docs: add skipLibCheck to README
Added the skipLibCheck flag to the README for the astro app
Resolves #62

docs: add skipLibCheck to README

---

.github/PULL_REQUEST_TEMPLATE.md

Add Pull Request template V.0.0.1

docs: add new pull request template #40

---

apps/docs-app/static/new/index.html

docs: add redirect to new project as static /new route

---

.github/ISSUE_TEMPLATE/01-bug-report.yml
.github/ISSUE_TEMPLATE/02-feature-request.yml
apps/docs-app/docs/packages/router/overview.md
apps/docs-app/sidebars.js
commitlint.config.js
packages/router/LICENSE
packages/router/README.md
packages/router/package.json
packages/router/project.json

docs(router): add initial documentation for router package

---

packages/router/README.md

docs(router): fix typo in the "Dynamic Routes" section (#123)

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
packages/vite-plugin-angular/src/lib/router-plugin.ts

Issue Number: #119
Temp fix for https://github.com/vitejs/vite/issues/10616

Fix invalidate routes

---

packages/astro-angular/README.md
packages/astro-angular/src/index.ts
packages/vite-plugin-angular/src/index.ts
packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

feat(astro-angular): add ability to pass vite options to integration

---

README.md

docs: add link to Angular docs

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

closes #134
Issue Number: #134

fix(vite-plugin-angular): fix parsing of tsconfig option

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

closes #112
Issue Number: #112

feat(vite-plugin-angular): support Angular Material custom package.json exports

---

.github/PULL_REQUEST_TEMPLATE.md
packages/router/README.md

docs: update manual install instructions for router

---

packages/create-analog/template-angular-v14/src/app/app.component.spec.ts
packages/create-analog/template-angular-v14/src/app/app.component.ts
packages/create-analog/template-angular-v14/src/app/routes/index.ts
packages/create-analog/template-angular-v14/src/main.ts
packages/create-analog/template-angular-v14/src/server/routes/v1/hello.ts
packages/create-analog/template-angular-v14/src/styles.css

fix(create-analog): register router and initial client/server routes

---

netlify.toml
packages/platform/src/lib/vite-nitro-plugin.ts

build: add netlify deployment for example app

---

apps/docs-app/docs/introduction.md

docs: fix typo in features

---

.all-contributorsrc
apps/docs-app/docs/contributors.mdx

docs: add info from add-contributors to docs

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

When using Angular Material components/styles there's no error.

fix(vite-plugin-angular): remove sass from resolve conditions

---

apps/docs-app/docs/packages/create-analog/overview.md

docs: add tailwind in overview

---

apps/analog-app/vite.config.ts
packages/platform/project.json
packages/platform/src/lib/runtime/api-middleware.js
packages/platform/src/lib/runtime/api-middleware.ts
packages/platform/src/lib/runtime/renderer.js

If routes are provided for pre-rendering, the build finishes successfully

fix(platform): convert runtime files to JS for pre-rendering

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

`sass` was removed in a previous PR, but it should just be included after `style` to support Angular Material custom themes

fix: add condition for sass styles

---

packages/astro-angular/src/server.ts

fix(astro-angular): update zone.js import to zone.js/node

---

packages/platform/src/lib/vite-nitro-plugin.ts

fix(platform): only apply nitro SSR options during build

---

apps/docs-app/docs/getting-started.md

Added the node and Angular version requirements to the docs
Closes #92
Issue Number: 92
Closes #92

Add System Requirements to Docs

---

.github/ISSUE_TEMPLATE/01-bug-report.yml
.github/ISSUE_TEMPLATE/02-feature-request.yml
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Add missing scope to the github templates and contributing doc.

chore: update github templates

---

packages/create-analog/template-angular-v15/package.json

When using Nx 15.4.x, the template application doesn't work using the standalone @nrwl/vite builder.
The template application works with Nx 15.4

fix(create-analog): add @nrwl/angular package to support Nx 15.4.x

---

apps/blog-app/index.html
apps/blog-app/src/content/2022-12-31-my-second-post.md
apps/blog-app/src/main.ts
packages/content/src/lib/anchor-navigation.directive.spec.ts
packages/content/src/lib/anchor-navigation.directive.ts
packages/content/src/lib/markdown.component.ts

The app will be hard refreshed when the user clicks on the internal link defined in the markdown file.
The app won't be hard refreshed when the user clicks on the internal link defined in the markdown file.
The behavior remains the same for external links, internal links with `target="_blank`, and links with `download` attribute.

feat(content): use angular router for internal links

---

apps/docs-app/docs/packages/create-analog/overview.md
packages/create-analog/README.md

docs(create-analog): add angular-v15 template to overview

---

apps/analog-app/src/app/routes/(home).ts
apps/blog-app/src/app/routes/index.ts
packages/router/README.md
packages/router/src/index.ts
packages/router/src/lib/define-route.ts
packages/router/src/lib/models.ts
packages/router/src/lib/routes.spec.ts

feat(router): add `RouteMeta` type and deprecate `defineRouteMeta` in favor of `RouteMeta`

---

packages/platform/src/lib/vite-nitro-plugin.ts

fix(platform): add handling of routes array for prerendering

---

apps/blog-app/src/app/routes/blog.ts
apps/blog-app/src/content/2022-12-27-my-first-post.md
apps/blog-app/src/content/2022-12-31-my-second-post.md
packages/content/project.json
packages/content/src/index.ts
packages/content/src/lib/content-file.ts
packages/content/src/lib/content-files-token.spec.ts
packages/content/src/lib/content-files-token.ts
packages/content/src/lib/content.spec.ts
packages/content/src/lib/content.ts
packages/content/src/lib/get-raw-files.ts
packages/content/src/lib/inject-content-files.spec.ts
packages/content/src/lib/inject-content-files.ts

Not implemented
Behaves as described in: #222

Feature: add injectable token/service that provides list of content w/frontmatter

---

apps/docs-app/src/components/StackblitzButton/index.tsx

docs: fix link for StackBlitz button

---

apps/docs-app/docusaurus.config.js

docs: fix edit link

---

apps/docs-app/docusaurus.config.js
apps/docs-app/src/components/HomepageFeatures/styles.module.css
apps/docs-app/src/components/StackblitzButton/index.tsx
apps/docs-app/src/components/StackblitzButton/styles.module.css
apps/docs-app/src/css/custom.css
apps/docs-app/src/pages/index.module.css
apps/docs-app/src/pages/index.tsx

docs: use dark blue palette in dark mode

---

apps/docs-app/docs/features/routing/overview.md

docs(content): add how to redirect to a default route

---

packages/astro-angular/package.json
packages/content/package.json
packages/router/package.json
packages/vite-plugin-angular/package.json

feat: update package.json deps for Angular v16 support

---

apps/docs-app/static/new/index.html

fix: add working StackBlitz link

---

packages/platform/src/lib/runtime/api-middleware.js

Fixes an issue with API routes not being found when deployed on Netlify

fix(platform): use slash in event handler for apiPrefix

---

apps/docs-app/docs/features/deployment/overview.md
apps/docs-app/docs/features/deployment/providers.md
apps/docs-app/docs/getting-started.md
apps/docs-app/sidebars.js

- renamed section from "Build & Deploy" to "Deployment"
- moved build command descriptions to "Getting Started" page
- updated Deployment Overview page with command to run prod server
- added "Providers" page with guide for [Render.com](https://render.com)
Refs: #324
Issue Number: #324

docs: update "build & deploy" section - add render.com deploy guide

---

packages/router/src/lib/routes.spec.ts
packages/router/src/lib/routes.ts

fix(router): update regex to correctly parse catch-all routes

---

packages/create-analog/template-angular-v15/src/app/pages/index.page.ts
packages/create-analog/template-angular-v16-prerelease/src/app/pages/index.page.ts

chore(create-analog): update templates to Analog logo and docs link

---

apps/docs-app/docs/features/server/server-side-rendering.md
apps/docs-app/docs/features/server/static-site-generation.md

docs: add examples for SSR compatibility and static pages

---

apps/docs-app/docs/features/deployment/providers.md

docs: add Edgio as another deployment provider

---

packages/platform/src/lib/ssr/dev-server-plugin.ts

When a compilation error occurs, the dev server stops
When a compilation error occurs, the dev server continues running and displays the error overlay

fix(platform): display error overlay in SSR mode

---

apps/astro-app/src/components/card.component.ts
apps/astro-app/src/components/todos.component.ts
apps/astro-app/src/pages/index.astro
packages/astro-angular/README.md
packages/astro-angular/src/client.ts
packages/astro-angular/src/index.ts
packages/astro-angular/src/server.ts
packages/astro-angular/tsconfig.lib.json

Closes #97
Components can define providers that are used during static rendering and client hydration.

feat(astro-angular): add support for render and client component providers

---

packages/astro-angular/README.md

Copying `astro add @analogjs/astro-angular` from the docs fails.
Providing astro add command for different package managers, like astro does for their integrations.

docs: update astro add command

---

packages/create-analog/template-angular-v15/README.md
packages/create-analog/template-angular-v15/angular.json
packages/create-analog/template-angular-v16/README.md
packages/create-analog/template-angular-v16/angular.json
packages/nx-plugin/src/generators/app/lib/add-analog-project-config.ts

- Updates serve/build/test commands to npm
- Adds `maint` entry to angular.json for `ng add` support
- Adds sponsor link to community section

chore: update README copy and template app configuration

---

packages/nx-plugin/src/generators/app/lib/initialize-analog-workspace.ts
packages/nx-plugin/src/generators/preset/generator.spec.ts
packages/nx-plugin/src/generators/preset/schema.d.ts
packages/nx-plugin/src/generators/preset/schema.json

fix(nx-plugin): add missing properties to preset generator schema.json

---

apps/docs-app/docs/features/deployment/providers.md

Deployment docs are adding for deploying Analog apps to Firebase with Cloud Functions

docs: add deployment docs for Firebase

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

Closes #383 
JIT mode builds correctly

fix(vite-plugin-angular): correctly inline external styles/templates in JIT mode

---

apps/docs-app/docs/features/routing/content.md
apps/docs-app/docs/features/routing/overview.md

- [x ] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ x] Docs have been added / updated (for bug fixes / features)

docs: update routing docs: 'pages' instead of 'routes'

---

README.md

I didn't easily find links to Analog's socials. 
Added badges to the README.md to easily follow on twitter or join the discord server.

docs: add discord and twitter badges to README.md

---

apps/docs-app/docs/features/server/server-side-rendering.md

docs: ensure code block is closed

---

apps/blog-app/src/app/app.config.ts
package.json
packages/platform/package.json
packages/vite-plugin-nitro/package.json
packages/vite-plugin-nitro/src/lib/vite-nitro-plugin.spec.data.ts
packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
yarn.lock

Upgraded to Nitro 2.x which has updated features including additional presets and support for Vercel KV.

feat(vite-plugin-nitro): upgrade Nitro dependency to 2.x

---

nx.json
package.json
pnpm-lock.yaml

ci: add caching with Nx Cloud

---

.github/ISSUE_TEMPLATE/01-bug-report.yml
.github/ISSUE_TEMPLATE/02-feature-request.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml

ci: update GitHub templates and action workflows

---

packages/nx-plugin/project.json

build: add implicit dependency on nx-plugin to platform package

---

packages/router/src/lib/routes.spec.ts
packages/router/src/lib/routes.ts

- It's not possible to create named nested pages without a parent (layout) page.
- Creating pages within the pathless directory and pathless layouts are not supported.
Closes #237, #273
- We can create named nested routes without a layout route.
```
/pages
/blog
posts.page.ts
```
- We can create pages within the pathless directories.
```
/pages
/(auth)
login.page.ts
signup.page.ts
```
- We can define the layout page for pages within the pathless directory.
```
/pages
/(auth)
login.page.ts
signup.page.ts
(auth).page.ts
```
- We can create nested wildcard routes:
```
/pages
/blog
posts.page.ts
[...blog-not-found].md
blog.page.ts
index.page.ts
[...not-found].md
```
**EDIT:** 😅

feat(router): overhaul route discovery engine

---

packages/trpc/src/index.ts
packages/trpc/src/lib/client/trpc-rxjs-proxy.ts

closes #447
Type is private and cannot be used outside of @analogjs/trpc
Closes #447

feat(trpc): make CreateTRPCProxyClient publicly available

---

.gitignore
apps/analog-app/vite.config.ts

Closes #
Netlify deploy previews and production deployments have the correct URL

ci: generate VITE_ANALOG_PUBLIC_BASE_URL for Netlify deployment

---

apps/analog-app/vite.config.ts
packages/platform/project.json

Closes #
Prevents overlap in Netlify and GitHub Actions CI environments

ci: use Netlify environment variable for CI check

---

packages/astro-angular/tsconfig.lib.json

A message is logged to the console when using the `astro-angular` package about missing sourcemaps
Closes #423 
No message is logged to the console when using the `astro-angular` package about missing sourcemaps

fix(astro-angular): fix sourcemaps for build

---

packages/astro-angular/README.md

Update  tsconfig.app.json file
Bug:
https://github.com/analogjs/analog/issues/460
Closes #

docs(astro-angular): update setup instructions to disallow js by default (#460)

---

apps/docs-app/docs/features/routing/content.md

docs: fix example code for content filter

---

packages/platform/src/lib/router-plugin.ts

Closes #445 
Common Angular packages are transformed as part of using SSR out of the box.

fix: add common Angular libraries for ssr transform

---

.gitignore
apps/create-analog-e2e/project.json
apps/create-analog-e2e/tests/create-analog.spec.ts
apps/create-analog-e2e/vite.config.ts

Closes #
An e2e test is run for the create-analog project

build: add e2e app for create-analog

---

apps/analog-preset-e2e/project.json
apps/analog-preset-e2e/tests/analog-preset.spec.ts
apps/analog-preset-e2e/vite.config.ts
packages/nx-plugin/src/generators/preset/schema.json

Closes #
An e2e test verifies that `create-nx-workspace` works correctly with the `@analogjs/platform` preset

build: add e2e test for Nx workspace with @analogjs/platform preset

---

apps/docs-app/docs/features/testing/vitest.md
apps/docs-app/docs/features/updating/overview.md
apps/docs-app/docs/getting-started.md
apps/docs-app/docs/integrations/nx/index.md
apps/docs-app/docs/introduction.md
apps/docs-app/sidebars.js

Closes #
- Getting started refers to create-analog with a reference to the integration within Nx
- A new section for creating a standalone Nx project with the platform preset
- A new section for generating an Analog app within an existing Nx workspace

docs: add page for Nx to integrations

---

packages/platform/src/lib/clear-client-page-endpoint.ts
packages/platform/src/lib/router-plugin.ts
packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

Closes #
- Adds a fallback root for vite-plugin-angular so it can be used standalone in Cypress Component Testing
- Only apply clearing page endpoints on build to prevent errors in development
- Adds Angular deps to be optimized that are transitively included

fix: vite-plugin-angular and platform fixes

---

apps/docs-app/docs/integrations/nx/index.md

Nx is not using latest as the recommended way of initiating an Analog project using NX
Updated to recommend @latest as the proper way to scaffold an Nx project.

docs: update nx start script to use @latest

---

apps/docs-app/docs/features/server/static-site-generation.md

Docs currently state SSG content should be deployed from an incorrect build directory
Updated docs of where SSG content can be deployed from

docs: update where static pages can be deployed from

---

.gitignore
packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

https://github.com/analogjs/analog/issues/503
Feature: add transform filter to Vite plugin
Closes #503
Closes #440
@analogjs/astro-angular  Config e.g
```typescript
analogjsangular(
{
vite: {
transformFilter: (code, id) => {
if (id.includes('/pages')) {
return false;
}
}
}
}
)
```
or
```typescript
analogjsangular(
{
vite: {
transformFilter: (code, id) => {
if (code.includes('@NgModule') || code.includes('@Component) || .......etc) {
return true;
}
return false;
}
}
}
)
```

fix: add transform filter to vite plugin

---

.github/ISSUE_TEMPLATE/01-bug-report.yml

Update the stackblitz example URL
Fixes #529
Closes #

docs: update 01-bug-report.yml

---

.github/workflows/ci.yml
packages/astro-angular/project.json
packages/content/project.json
packages/nx-plugin/project.json
packages/platform/project.json
packages/trpc/project.json
packages/vite-plugin-angular/project.json
packages/vite-plugin-nitro/project.json

Closes #
Nx Cloud cache is updated on merges to the main branch, and when team members branches pushed up to the repository.

ci: add Nx Cloud token to update cache on main

---

package.json
packages/nx-plugin/generators.json
packages/nx-plugin/src/generators/app/generator.spec.ts
packages/nx-plugin/src/generators/app/generator.ts
packages/nx-plugin/src/generators/app/lib/add-analog-project-config.ts
packages/nx-plugin/src/generators/app/lib/add-eslint.ts
pnpm-lock.yaml

Creating a new Nx workspace with the Analog preset adds a linting target, however it does not install the necessary eslint dependencies or create the eslintrc file at the root of the repository.
This utilizes the Nx eslint generator to setup linting, add dependencies and create configuration files. Also corrected the schematic description.

fix(nx-plugin): fixing linting in nx project

---

packages/astro-angular/README.md

when using `client:load`
Documenting #537

docs(astro-angular): describe config to transform external package

---

apps/docs-app/docs/features/routing/metadata.md

docs(router): add guide for nested redirect routes

---

apps/blog-app/src/app/app.config.ts
packages/content/src/index.ts
packages/content/src/lib/markdown-content-renderer.service.ts
packages/content/src/lib/marked-setup.service.ts

- A warning is displayed in the console that the toolbar is not loaded before the copy clipboard plugin for Prism
- The mermaid code is parsed/bundled even when not being used
Closes #
- The toolbar is loaded before the copy clipboard plugin for Prism
- The mermaid code is loaded through the `withMarkdownRenderer()` provider function
```ts
import { provideContent, withMarkdownRenderer } from '@analogjs/content';
import { provideFileRouter } from '@analogjs/router';
import { provideHttpClient } from '@angular/common/http';
import { ApplicationConfig } from '@angular/core';
import { provideClientHydration } from '@angular/platform-browser';
import {
withEnabledBlockingInitialNavigation, …
```

fix(content): ensure prism toolbar is loaded first, use external mermaid loader

---

packages/create-analog/template-angular-v15/package.json
packages/create-analog/template-angular-v16/package.json
packages/nx-plugin/src/generators/app/generator.spec.ts
packages/nx-plugin/src/generators/app/versions.ts
packages/nx-plugin/src/generators/app/versions/dependencies.ts
packages/nx-plugin/src/generators/app/versions/nx_15_X/versions.ts
packages/nx-plugin/src/generators/app/versions/nx_16_X/versions.ts

The `mermaid` dependency is not installed when the Nx preset is used or installed with new projects.
Closes #
The `mermaid` dependency is installed when the Nx preset is used or the creation of a new project.

fix: add mermaid dependency to new projects

---

package.json
packages/astro-angular/package.json
packages/content/package.json
packages/create-analog/template-angular-v15/package.json
packages/create-analog/template-angular-v16/package.json
packages/nx-plugin/src/generators/app/generator.spec.ts
packages/nx-plugin/src/generators/app/versions/nx_16_X/versions.ts
packages/platform/package.json
packages/router/package.json
packages/trpc/package.json
packages/vite-plugin-angular/package.json
packages/vite-plugin-nitro/package.json

chore: release 0.2.0-rc.0

---

apps/docs-app/docs/features/routing/content.md
apps/docs-app/docs/features/routing/overview.md

docs(router): add section that combines all types of routes

---

.githooks/commit-msg
.githooks/pre-commit
package.json

"commit-msg" hook fails on Windows:
"commit-msg" hook works on Windows ✅

chore: fix commitlint on Windows

---

package.json
packages/vite-plugin-nitro/src/lib/plugins/page-endpoints.ts
pnpm-lock.yaml

If you define a `.server` file without a `load` function, you'd receive an error.
Closes #
If you define a `.server` file without a `load` function, a stub load function is added. This allows us to expand the `.server` extension for other use cases that don't require a `load` function.

fix(vite-plugin-nitro): add check for exported load function for page endpoints

---

apps/create-analog-e2e/tests/create-analog.spec.ts
packages/vite-plugin-angular/src/lib/utils/devkit.ts

fix(vite-plugin-angular): add compatibility support for Angular v16.2+

---

apps/analog-app-e2e-cypress/src/e2e/app.cy.ts
apps/analog-app-e2e-cypress/src/support/app.po.ts
apps/analog-app/src/app/cart.service.ts
apps/analog-app/src/app/pages/[...slug].page.ts
apps/analog-app/src/app/pages/[...slug].server.ts
apps/analog-app/src/app/pages/shipping/[...slug].page.ts
apps/analog-app/src/app/pages/shipping/[...slug].server.ts
apps/analog-app/src/public/assets/shipping.json
apps/analog-app/src/vite-env.d.ts
packages/router/src/lib/route-config.ts
packages/router/src/lib/routes.ts
packages/vite-plugin-nitro/src/lib/utils/get-page-handlers.ts

When using a `.server.ts` file with a catch-all route, the server-side data fetching returns a 404.
Closes #
When using a `.server.ts` file with a catch-all route, the server-side data fetching builds a valid route.

fix(router): add support for server-side data fetching with catch-all routes

---

packages/vite-plugin-nitro/src/lib/plugins/page-endpoints.ts
packages/vite-plugin-nitro/src/lib/utils/get-page-handlers.ts

fix(vite-plugin-nitro): normalize page handler path for Windows (#591)

---

apps/docs-app/docs/features/routing/overview.md

docs: cleanup import in routing/overview.md
Update documentation in routing/overview.md to reflect correct / missing imports in the examples.
Documentation is either missing an import or has too many unnecessary imports
Closes #

docs: cleanup imports in routing/overview examples

---

apps/docs-app/docs/features/deployment/providers.md

docs(vite-plugin-nitro): add guide to deploy on netlify

---

apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current.json
apps/docs-app/sidebars.js

Closes #
There are 3 sections in sidebar translated to Spanish by error.
Thanks to @rlmestre for let me know about this issue. 
best describes this PR or how it makes you feel?
>

doc: update spanish translated sections by error in sidebar.js

---

packages/platform/src/lib/platform-plugin.ts
packages/platform/src/lib/ssr/ssr-build-plugin.ts
packages/platform/src/lib/ssr/ssr-xhr-plugin.ts

Building for non-node environments such as Cloudflare pages/workers is not supported out of the box
Closes #
- re-defines `global` as `globalThis`
- Patches `node` dependencies in the `xhr2` package
- Adds the `xhr2` package to the SSR transform list

feat: add support for non-node/Cloudflare builds

---

package.json
packages/create-analog/package.json

build(create-analog): remove support for node 16

---

packages/platform/src/lib/ssr/ssr-build-plugin.ts
packages/platform/src/lib/ssr/ssr-xhr-plugin.ts
packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
tsconfig.base.json

Closes #
`global` as define variable is removed, as its statically replaced

fix(platform): remove global define, update platform-server replacements

---

nx.json

Nx Cloud light client is not enabled
Nx Cloud light client is enabled

build: enable nx-cloud light client

---

apps/docs-app/docusaurus.config.js
apps/docs-app/i18n/fr/code.json
apps/docs-app/i18n/fr/docusaurus-plugin-content-docs/current.json
apps/docs-app/i18n/fr/docusaurus-theme-classic/footer.json
apps/docs-app/i18n/fr/docusaurus-theme-classic/navbar.json

Closes #
- Add new `fr` locale
- Add full French translation to analogjs website.
- Add french translation to docs sidenav.
Thanks @Villanuevand for your work on #644; it greatly assisted in integrating a new language!

docs(content): add website french translation

---

packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts

When building for Cloudflare, manual configuration is needed to include zone.js/node with side effects in the server build
Closes #
- When building for Cloudflare, no manual configuration is needed to include zone.js/node with side effects in the server build.
-  Compatible with zone.js >= 0.13.x

fix(vite-plugin-nitro): update import detection for zone.js in node

---

apps/docs-app/docusaurus.config.js
apps/docs-app/i18n/pt-br/code.json
apps/docs-app/i18n/pt-br/docusaurus-plugin-content-docs/current.json
apps/docs-app/i18n/pt-br/docusaurus-theme-classic/footer.json
apps/docs-app/i18n/pt-br/docusaurus-theme-classic/navbar.json

docs(content): add website brazilian portuguese translation

---

apps/docs-app/docs/features/deployment/providers.md

Closes #
- Adds deployment guide for Cloudflare pages and workers
- Reorganizes provider sections

docs: add deployment guide for Cloudflare Pages and Workers

---

apps/docs-app/docusaurus.config.js
apps/docs-app/i18n/tr/code.json
apps/docs-app/i18n/tr/docusaurus-plugin-content-docs/current.json
apps/docs-app/i18n/tr/docusaurus-theme-classic/footer.json
apps/docs-app/i18n/tr/docusaurus-theme-classic/navbar.json

docs(content): add turkish translation

---

apps/astro-app-e2e-playwright/tests/app.spec.ts
apps/astro-app/astro.config.mjs
apps/astro-app/src/pages/test.mdx
package.json
packages/astro-angular/README.md
packages/astro-angular/src/index.spec.ts
packages/astro-angular/src/index.ts
pnpm-lock.yaml

fix(astro-angular): warn about shiki in mdx astro integration and override with prism

---

apps/docs-app/docs/features/data-fetching/server-side-data-fetching.md
apps/docs-app/sidebars.js

docs: add server-side data fetching

---

CHANGELOG.md

chore: add initial changelog

---

packages/nx-plugin/src/generators/app/lib/initialize-analog-workspace.ts

Currently using Nx version 17 fails as we try to pick the @nrwl namespace instead of the @nx namespace.
Closes #
Uses @nx namespace for projects of version 16 and up

fix(nx-plugin): use nx namespace for any nx version above version 16

---

README.md

docs: add pnpm example to readme

---

packages/vite-plugin-nitro/src/lib/plugins/dev-server-plugin.ts

fix(vite-plugin-nitro): Add `Content-Type` header for responses (#712).

---

apps/docs-app/docs/features/routing/content.md

Closes https://github.com/analogjs/analog/issues/609

docs: add mermaid configuration to content routes

---

.github/ISSUE_TEMPLATE/01-bug-report.yml

chore: fix link to analog stackblitz example

---

packages/content/src/lib/marked-setup.service.ts
packages/content/src/lib/prism/angular.js
packages/content/tsconfig.lib.json

feat(content): add prism angular @-syntax support

---

packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts

fix(vite-plugin-nitro): add zone.js import for cloudflare, config overrides

---

packages/content/src/lib/prism/angular.js

An error is thrown on the server when loading the angular plugin for Prism
Closes #
If Prism is not defined, the plugin does a noop.

fix(content): add check for defined Prism

---

README.md

In current Readme the twitter logo is not visible and logo is not updated to X.
Closes #737 
Updated the twitter logo in Readme to X

docs: Update twitter logo to X

---

packages/platform/package.json

Changing how dependencies are installed
`@nx/devkit` is installed along with `@analog/platform` but it is only used for development.
`@nx/devkit` is only installed for development.

chore(platform): move `@nx/devkit` to dev dependencies

---

README.md
apps/astro-app/src/pages/index.astro
apps/astro-app/src/pages/test.mdx
apps/docs-app/docs/introduction.md
apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current/introduction.md
packages/astro-angular/README.md
packages/vite-plugin-angular/src/lib/compiler-plugin.ts
packages/vite-plugin-nitro/src/lib/utils/load-esm.ts

The angular link points to angular.io website
Closes #
The angular link will point to angular.dev website

docs: update link to point new angular.dev site

---

apps/docs-app/docs/features/deployment/providers.md

The Netlify provider documentation is outdated.
Closes #
The Netlify provider documentation focus on the simple tasks required.
Happy to update the documentation for the future ourselves!

docs: update Netlify provider configuration

---

apps/docs-app/docs/features/testing/vitest.md
packages/nx-plugin/generators.json
packages/nx-plugin/src/generators/setup-vitest/compat.ts
packages/nx-plugin/src/generators/setup-vitest/files/src/test-setup.ts__template__
packages/nx-plugin/src/generators/setup-vitest/files/vite.config.ts__template__
packages/nx-plugin/src/generators/setup-vitest/generator.ts
packages/nx-plugin/src/generators/setup-vitest/lib/add-analog-dependencies.ts
packages/nx-plugin/src/generators/setup-vitest/lib/update-test-target.ts
packages/nx-plugin/src/generators/setup-vitest/lib/update-tsconfig.ts
packages/nx-plugin/src/generators/setup-vitest/schema.d.ts
packages/nx-plugin/src/generators/setup-vitest/schema.json
packages/nx-plugin/src/generators/setup-vitest/versions/dev-dependencies.ts
packages/nx-plugin/src/generators/setup-vitest/versions/ng_16_X/versions.ts
packages/nx-plugin/src/generators/setup-vitest/versions/ng_17_X/versions.ts
packages/platform/package.json

Closes #451 
- Adds a `setup-vitest` schematic/generator to setup the initial files and configuration for running Vitest
- Works with Angular CLI and Nx workspaces
Install
```sh
npm i @analogjs/platform --save-dev
```
Run
```sh
ng g @analogjs/platform:setup-vitest [your-project-name]
```

feat(nx-plugin): add schematic to setup Vitest for existing Angular projects

---

CONTRIBUTING.md

docs: add details to contributing.md

---

apps/create-analog-e2e/tests/create-analog.spec.ts

chore: fix path checks for create-analog e2e tests

---

apps/docs-app/docs/features/testing/vitest.md

docs: add snapshot testing with vitest

---

packages/vite-plugin-angular/src/lib/angular-vitest-plugin.ts

All packages containing `fesm2022` in the filename were transformed to es2016 using esbuild. This causes slower performance when running tests with Vitest in Angular.
Closes #
By default, only filenames containing `cdk/fesm2022` are transformed using esbuild. This drastically improves performance when running tests with Vitest in Angular, while keeping compatibility with existing tests.
Additional files can be added to the transform using the `ssr.noExternal` array in the `vite.config.ts` but this satisfies using Angular component harness tests as well as regular unit tests using async/await.

perf(vite-plugin-angular): only filter to Angular CDK packages for ESM transform

---

apps/docs-app/docs/features/deployment/providers.md

docs: add a docs section for Github Pages Deployment

---

apps/docs-app/docs/features/server/server-side-rendering.md
apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current/features/server/server-side-rendering.md

I assume this is meant to reference the @spartan-ng libs. Took me a minute to realize it was missing the '-ng' when using analog with @spartan-ng/ui.
Closes #

docs(content): @spartan -> @spartan-ng

---

apps/ng-app/src/app/hello.ng
packages/vite-plugin-angular/src/lib/authoring/__snapshots__/ng.spec.ts.snap
packages/vite-plugin-angular/src/lib/authoring/ng.spec.ts
packages/vite-plugin-angular/src/lib/authoring/ng.ts

Destructuring in `.ng` files didn't work
Closes #
Destructuring in `.ng` files should work
```html
<script lang="ts">
const [a, b, , c = 5] = [1, 2, 3];
const { foo: aliasFoo, bar = 'defaultValue' } = { foo: 'chau' };
</script>
```
becomes
```ts
constructor() {
const [a, b, , c = 5] = [1, 2, 3];
this.a = a;
this.b = b;
this.c = c;
const { foo: aliasFoo, bar = 'defaultValue' } = { foo: 'chau' };
this.aliasFoo = aliasFoo;
this.bar = bar;
}
```

fix(vite-plugin-angular): add support for destructuring in .ng files

---

packages/vite-plugin-angular/src/index.ts
packages/vite-plugin-angular/src/lib/authoring/ng.spec.ts
packages/vite-plugin-angular/src/lib/authoring/ng.ts
packages/vite-plugin-angular/src/lib/host.ts

feat(vite-plugin-angular): expose compileNgFile as public API

---

apps/ng-app/src/app/app.component.ng
apps/ng-app/src/app/app.config.ts
apps/ng-app/src/app/pages/(home).page.ng
apps/ng-app/src/app/pages/about.page.ng
packages/router/src/lib/routes.ts

Filesystem-based routing does not collect `.page.ng` files for building pages.
Closes #
Filesystem-based routing collects `.page.ng` files for building pages.

feat(router): add filesystem-based routing support for .ng files

---

packages/vite-plugin-angular/src/lib/authoring/__snapshots__/ng.spec.ts.snap
packages/vite-plugin-angular/src/lib/authoring/ng.spec.ts
packages/vite-plugin-angular/src/lib/authoring/ng.ts

fix(vite-plugin-angular): adjust compiled output to be more concise

---

packages/vite-plugin-angular/setup-vitest.ts

Closes #
Adds better support for detecting snapshot fixtures and instances

fix(vite-plugin-angular): improve support for Angular snapshot detection

---

packages/platform/src/lib/router-plugin.ts

```
[vite] Error when evaluating SSR module /src/app/pages/home.page.ts: failed to import "rxfire/auth"
t "rxfire/auth"
|- **/node_modules/rxfire/auth/index.esm.js:1
import { onAuthStateChanged, onIdTokenChanged, getIdToken } from 'firebase/auth';
^^^^^^
```
Closes #
rxfire libraries can be imported using SSR without error

fix(platform): add SSR support for rxfire packages

---

packages/vite-plugin-angular/src/lib/compiler-plugin.ts

Closes #
Fixes an issue where the `ReactiveFormsModule` is added to the `imports` of a standalone component, but the directives were not being registered on the form.

fix(vite-plugin-angular): force jit flag in JavaScript transformer

---

packages/nx-plugin/src/generators/page/__snapshots__/generator.spec.ts.snap
packages/nx-plugin/src/generators/page/generator.spec.ts
packages/nx-plugin/src/generators/page/generator.ts

Page is not generating properly under certain scenarios ex.
npx nx generate @analogjs/platform:page --pathname='(customers)'/demo/home --project=demoApp --no-interactive --dry-run
will generate:
demoApp/src/app/pages/(customers),demo/home.page.ts
Closes #860 
Page is generated properly
demoApp/src/app/pages/(customers)/demo/home.page.ts

fix(nx-plugin): change logic to join folder for page generation

---

packages/vite-plugin-angular/src/lib/authoring/__snapshots__/ng.spec.ts.snap
packages/vite-plugin-angular/src/lib/authoring/ng.ts

Refactor `processNgScript` to use for loop to reduce the amount of nested ifs

refactor(vite-plugin-angular): use for loop with continue statement

---

package.json
pnpm-lock.yaml

build: update Vitest to 1.2.1

---

.prettierignore
apps/ng-app/index.html
apps/ng-app/src/app/app.config.ts
apps/ng-app/src/app/pages/about.page.analog
apps/ng-app/src/styles.css
packages/content/src/index.ts
packages/vite-plugin-angular/src/lib/authoring/__snapshots__/analog.spec.ts.snap
packages/vite-plugin-angular/src/lib/authoring/analog.spec.ts
packages/vite-plugin-angular/src/lib/authoring/analog.ts
packages/vite-plugin-angular/src/lib/authoring/constants.ts
packages/vite-plugin-angular/src/lib/authoring/marked-setup.service.ts
packages/vite-plugin-angular/src/lib/host.ts

Closes #
An inline template for a `.analog` file supports authoring with markdown. This template is compiled into HTML and used as the component template, allowing for Angular syntax and components to be used.
```html
<script lang="ts">
import Hello from '../hello.analog';
</script>
<template lang="md">
'''sh
npm create analog
'''
<Hello />
</template>
```
Result:
NOTE: The same constraints exist for an Angular component template, such as using `@` directly, interpolation tags, and more.

feat(vite-plugin-angular): add inline markdown support to analog template

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
packages/vite-plugin-angular/src/lib/component-resolvers.spec.ts
packages/vite-plugin-angular/src/lib/component-resolvers.ts

fix(vite-plugin-angular): extract `styleUrl`s using AST

---

packages/nx-plugin/src/generators/app/files/tailwind/tailwind.config.js__template__
packages/nx-plugin/src/generators/app/generator.spec.ts
packages/nx-plugin/src/generators/app/generator.ts
packages/nx-plugin/src/generators/app/lib/add-tailwind-config.ts
packages/nx-plugin/src/generators/app/lib/add-tailwind-helpers.ts
packages/nx-plugin/src/generators/app/versions/nx_15_X/versions.ts
packages/nx-plugin/src/generators/app/versions/nx_16_X/versions.ts
packages/nx-plugin/src/generators/app/versions/nx_17_X/versions.ts
packages/nx-plugin/src/generators/app/versions/nx_18_X/versions.ts
packages/nx-plugin/src/generators/app/versions/tailwind-dependencies.ts

There's an Error when creating a new Analog application using latest Nx (18) and choosing tailwind
Closes #
Application should generate properly.

fix(nx-plugin): update tailwind generator configuration for Nx 18

---

packages/nx-plugin/src/generators/app/lib/initialize-analog-workspace.ts

fix(nx-plugin): remove option from angular generator

---

packages/vite-plugin-angular/esbuild.ts
packages/vite-plugin-angular/project.json

feat(vite-plugin-angular): expose esbuild entry point

---

apps/ng-app/src/content/post.agx
packages/vite-plugin-angular/src/lib/host.ts

Attempting to use `<template lang="md">` in `.agx` files and attempting to render the component:
```ts
import(`../../content/${postId}.agx`).then(m => {
divPost.createComponent(m.default);
title.set(m.metadata.title);
cdr.detectChanges();
});
```
Will result in nothing being rendered (whereas is will work if just `<template>` is used)
`<template lang="md">` can successfully be used in `.agx` files to render markdown content

fix(vite-plugin-angular): check for agx.d in fileExists

---

package.json
packages/create-analog/package.json

When using node 20 you will get this warning: "Unsupported engine: wanted: {"node":"^18.13.0"} (current: {"node":"v20.11.1","pnpm":"8.9.0"})"
Closes #914 
no warning

chore: allow node 20

---

packages/router/src/index.ts

- The only way to interact with the File-based Router Mechanism is `provideFileRouter` function.
- It only has a set locations to monitor and doesn't have the ability to monitor custom locations for custom routes.
Closes #904 
Exported internals (createRoutes, Files, and RouteExport) enables developer to provide custom routes

feat(router): expose router internals for custom routers

---

apps/trpc-app/postcss.config.cjs
apps/trpc-app/tailwind.config.cjs
packages/nx-plugin/src/generators/app/files/tailwind/postcss.config.js__template__
packages/nx-plugin/src/generators/app/files/tailwind/tailwind.config.js__template__
packages/nx-plugin/src/generators/app/lib/add-files.ts
packages/nx-plugin/src/generators/app/lib/add-home-page.ts
packages/nx-plugin/src/generators/app/lib/add-tailwind-helpers.ts
packages/nx-plugin/src/generators/app/lib/add-trpc.ts
packages/nx-plugin/src/generators/page/generator.ts
packages/nx-plugin/src/generators/setup-vitest/generator.ts
packages/platform/src/lib/content-plugin.spec.ts
packages/platform/src/lib/content-plugin.ts
packages/platform/src/lib/options.ts
packages/vite-plugin-angular/src/lib/angular-jit-plugin.ts
packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
packages/vite-plugin-angular/src/lib/component-resolvers.spec.ts
packages/vite-plugin-angular/src/lib/component-resolvers.ts
packages/vite-plugin-nitro/src/lib/build-server.ts
packages/vite-plugin-nitro/src/lib/build-sitemap.spec.ts
packages/vite-plugin-nitro/src/lib/build-sitemap.ts
packages/vite-plugin-nitro/src/lib/build-ssr.ts
packages/vite-plugin-nitro/src/lib/plugins/dev-server-plugin.ts
packages/vite-plugin-nitro/src/lib/utils/get-content-files.ts
packages/vite-plugin-nitro/src/lib/utils/get-page-handlers.ts
packages/vite-plugin-nitro/src/lib/utils/load-esm.ts
packages/vite-plugin-nitro/src/lib/vite-nitro-plugin.spec.data.ts
packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
server.mjs
tools/scripts/publish.mjs

Closes #929 
"node:" prefixes added to node buildin modules

refactor: Node prefix

---

packages/nx-plugin/src/generators/app/files/template-angular-v17/package.json__template__
packages/nx-plugin/src/generators/app/files/template-angular-v17/vite.config.ts__template__
packages/nx-plugin/src/generators/app/generator.spec.ts
packages/nx-plugin/src/generators/app/versions/nx_17_X/versions.ts
packages/nx-plugin/src/generators/app/versions/nx_18_X/versions.ts
packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.spec.ts

Closes #
New Analog apps with Nx are generated with the latest release candidate.

fix(nx-plugin): update package versions to 1.0 RC

---

apps/docs-app/docs/features/routing/overview.md

 docs: remove redundant code lines

---

packages/create-analog/index.js

fix(create-analog): fixes postcss.config.cjs issue

---

packages/create-analog/template-angular-v17/src/app/pages/index.page.ts

fix(create-analog): removing unused css

---

apps/docs-app/docs/features/deployment/providers.md

Closes #
Cloudflare now uses advanced mode to configure the `_worker.js` for functions deployment

docs: use advanced mode with deployment for Cloudflare functions

---

apps/docs-app/docs/contributors.mdx
apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current/contributors.mdx

docs: update core contributors

---

apps/docs-app/docs/features/testing/vitest.md
apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current/features/testing/vitest.md

docs: improve vitest path aliases documentation

---

packages/platform/src/lib/router-plugin.ts

feat: add TanStack packages for SSR transform

---

apps/docs-app/docs/experimental/sfc/index.md
apps/ng-app/src/app/hello.analog
packages/vite-plugin-angular/src/lib/authoring/__snapshots__/analog.spec.ts.snap
packages/vite-plugin-angular/src/lib/authoring/analog.spec.ts
packages/vite-plugin-angular/src/lib/authoring/constants.ts

The `output` and `model` APIs for Signal components are not recognized with the Analog SFC.
Closes #
The `output` and `model` APIs for Signal components are recognized with the Analog SFC.

fix(vite-plugin-angular): add support for output and model Signal API to Analog SFC

---

apps/docs-app/docs/experimental/sfc/index.md

No `.agx` documentation
`.agx` documentation added to Analog SFCs docs

docs: add docs for agx files

---

apps/analog-app/src/main-cf.server.ts
apps/analog-app/vite.config.ts
apps/docs-app/docs/features/deployment/providers.md
packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts

Extra plugin configuration is needed to deploy to Cloudflare Pages
Closes #
No extra plugin configuration is needed to deploy to Cloudflare Pages

feat(vite-plugin-nitro): add internal deployment support for cloudflare

---

apps/docs-app/docusaurus.config.js

This PR adds the initial support for Algolia search. The problem is that the index does not appear to be ran
Closes #622

chore: add algolia support

---

packages/platform/src/lib/router-plugin.ts

fix(platform): add ngxtension to common packages for SSR

---

apps/docs-app/docs/features/generation/code-generation.md
apps/docs-app/docs/features/testing/vitest.md
packages/nx-plugin/src/generators/app/files/template-angular-v16/tsconfig.json__template__
packages/nx-plugin/src/generators/app/files/template-angular-v17/tsconfig.json__template__
packages/nx-plugin/src/generators/app/files/template-angular-v17/vite.config.ts__template__
packages/nx-plugin/src/generators/app/generator.spec.ts
packages/nx-plugin/src/generators/app/generator.ts
packages/nx-plugin/src/generators/app/lib/add-analog-project-config.ts
packages/nx-plugin/src/generators/app/lib/add-files.ts
packages/nx-plugin/src/generators/app/schema.json
packages/nx-plugin/src/generators/app/versions/dev-dependencies.ts
packages/nx-plugin/src/generators/app/versions/nx_17_X/versions.ts
packages/nx-plugin/src/generators/app/versions/nx_18_X/versions.ts

Using the application schematic in an Angular CLI workspace doesn't update the angular.json with the new project and doesn't generate the correct configuration and dependencies.
Closes #1021 
Using the application schematic in an Angular CLI workspace updates the angular.json with the new project, and generates the correct configuration and dependencies.

fix(nx-plugin): add support for app generator in Angular CLI workspaces

---

apps/analog-app/vite.config.ts
apps/blog-app/vite.config.ts
apps/ng-app/vite.config.ts
apps/trpc-app/vite.config.ts
packages/nx-plugin/src/generators/app/files/template-angular-v17/vite.config.ts__template__

Closes #1015 
Data binding should work when creating new project using Nx after deploying.

fix: remove commonjsOptions

---

README.md
apps/docs-app/docs/guides/migrating.md
apps/docs-app/docs/introduction.md
apps/docs-app/sidebars.js
packages/nx-plugin/generators.json
packages/nx-plugin/src/executors/vitest/schema.json
packages/nx-plugin/src/generators/init/compat.ts
packages/nx-plugin/src/generators/init/files/vite.config.ts__template__
packages/nx-plugin/src/generators/init/generator.ts
packages/nx-plugin/src/generators/init/lib/add-analog-dependencies.ts
packages/nx-plugin/src/generators/init/lib/update-app-tsconfig.ts
packages/nx-plugin/src/generators/init/lib/update-build-target.ts
packages/nx-plugin/src/generators/init/lib/update-index-html.ts
packages/nx-plugin/src/generators/init/lib/update-main.ts
packages/nx-plugin/src/generators/init/lib/update-package-json.ts
packages/nx-plugin/src/generators/init/lib/update-serve-target.ts
packages/nx-plugin/src/generators/init/lib/update-test-target.ts
packages/nx-plugin/src/generators/init/lib/update-test-tsconfig.ts
packages/nx-plugin/src/generators/init/schema.d.ts
packages/nx-plugin/src/generators/init/schema.json
packages/nx-plugin/src/generators/init/test-files/src/test-setup.ts__template__
packages/nx-plugin/src/generators/setup-vitest/versions/ng_16_X/versions.ts
packages/nx-plugin/src/generators/setup-vitest/versions/ng_17_X/versions.ts
packages/nx-plugin/src/utils/versions/dependencies.ts
packages/nx-plugin/src/utils/versions/dev-dependencies.ts
packages/nx-plugin/src/utils/versions/ng_16_X/versions.ts
packages/nx-plugin/src/utils/versions/ng_17_X/versions.ts
packages/vite-plugin-nitro/src/lib/build-server.ts

Closes https://github.com/analogjs/analog/issues/554
Installing the `@analogjs/platform` package and running `ng generate @analogjs/platform:init` runs a migration schematic to convert an existing Angular SPA to use Analog, Vite, and optionally Vitest.

feat(nx-plugin): add init schematic/generator for migrating an Angular SPA to Analog

---

packages/nx-plugin/src/generators/setup-vitest/files/vite.config.mts__template__
packages/nx-plugin/src/generators/setup-vitest/generator.ts

Closes #1056 
Adding `nxViteTsPaths` in NX workspace

fix(nx-plugin): add support for nx paths. fixes #1056

---

apps/docs-app/docs/integrations/ionic/index.md

Ionic Framework currently doesn't support Angular's new Client Hydration for SSR.
Adding additional content for ways to handle this.

docs: add SSR caveat to Ionic Framework docs

---

apps/docs-app/docs/features/deployment/providers.md
apps/docs-app/docusaurus.config.js

- link to netlify documentation for the different config settings
- specify that a build command is needed
- give an example netlify.toml
- add json, toml, and bash as highlighted languages
closes #1060
Closes #1060

docs: add more detail to netlify deploy docs for nx repos

---

apps/docs-app/docusaurus.config.js
apps/docs-app/i18n/ko/code.json
apps/docs-app/i18n/ko/docusaurus-plugin-content-docs/current.json
apps/docs-app/i18n/ko/docusaurus-theme-classic/footer.json
apps/docs-app/i18n/ko/docusaurus-theme-classic/navbar.json

Closes #
- Add new `ko` locale
- Add full korean translation to analogjs website.
- Add korean translation to docs sidenav.

docs(content): add website korean translation.

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

Closes #
Vitest can be run from within a StackBlitz environment

fix(vite-plugin-angular): add detection of StackBlitz environment for testing

---

packages/nx-plugin/src/executors/vitest/schema.json

A 301 is being returned for the schema, causing the executor to error
Closes #
No error is thrown when running the executor

fix(nx-plugin): remove $schema from vitest executor

---

apps/docs-app/docs/guides/migrating.md
packages/nx-plugin/src/generators/init/files/vite.config.ts__template__
packages/nx-plugin/src/utils/versions/dependencies.ts
packages/nx-plugin/src/utils/versions/dev-dependencies.ts
packages/nx-plugin/src/utils/versions/ng_15_X/versions.ts

Closes #
Adds correct dependencies to Angular v15 projects and updates installation instructions for migration.

fix(nx-plugin): adjust templates/docs for adding Analog to existing Angular projects

---

packages/create-analog/template-latest/package.json
release.config.cjs

fix(create-analog): add fixes for v18 template

---

packages/vite-plugin-angular/src/lib/angular-vitest-plugin.ts

Unit tests for components that import from `@analogjs/router` throw an error that `import.meta.glob` cannot be found. The `@analogjs/router` package is not processed by Vite to transform the glob into a map of files.
Closes #
Unit tests for components that import from `@analogjs/router` run without error.

fix(vite-plugin-angular): add @analogjs/router to vitest inline deps

---

.github/ISSUE_TEMPLATE/01-bug-report.yml
.github/ISSUE_TEMPLATE/02-feature-request.yml
.github/PULL_REQUEST_TEMPLATE.md
commitlint.config.cjs
package.json
packages/astro-angular/package.json
packages/content/package.json
packages/router/package.json
packages/trpc/package.json
packages/vite-plugin-angular/package.json
packages/vite-plugin-nitro/package.json
packages/vitest-angular/.eslintrc.json
packages/vitest-angular/README.md
packages/vitest-angular/builders.json
packages/vitest-angular/package.json
packages/vitest-angular/project.json
packages/vitest-angular/setup.ts
packages/vitest-angular/src/index.ts
packages/vitest-angular/src/lib/LICENSE.nx.md
packages/vitest-angular/src/lib/schema.d.ts
packages/vitest-angular/src/lib/schema.json
packages/vitest-angular/src/lib/vitest.impl.ts
packages/vitest-angular/tsconfig.json
packages/vitest-angular/tsconfig.lib.json
pnpm-lock.yaml
release.config.cjs
tools/publish.sh
tsconfig.base.json

Closes #993 
This introduces a new `@analogjs/vitest-angular` package that includes the `@analogjs/vitest-angular:test` builder for running tests with Vitest and Angular without any external dependencies.
- Angular CLII workspaces are supported
- Nx Workspaces are supported
- Using the Vitest CLI is supported

feat: introduce vitest-angular package

---

packages/nx-plugin/src/generators/app/lib/initialize-analog-workspace.ts

the newest angular compiler requires TypeScript >=5.4.0 and <5.5.0
Closes #

fix(nx-plugin): update typescript dependency

---

packages/content/src/lib/content.spec.ts
packages/content/src/lib/content.ts

Closes #981
the content stream is never finished so this is blocking piped use cases with `forkJoin`
example:
```ts
// resolver which returns an observable
export function injectBlogPosts() {
const contentFiles = injectContentFiles<PostAttributes>();
const contentStream = contentFiles.map((contentFile) => {
const parts = contentFile.filename.split('/');
const filename = parts[4];
return injectContent({
customFilename: `blog/${filename.split('.md').join('')}`
});
});
return forkJoin(contentStream);
}
```
```ts
// the component consuming it
export default class BlogsComponent {
posts = toSignal(injectBlogPosts());
}
```
```html
@for (post of posts()) {
<h1>{{post.attributes.title}}</h1> …
```

fix(content):  getContentFile stream should be finished

---

apps/analog-app-e2e-cypress/project.json
apps/analog-app-e2e-playwright/project.json
apps/analog-app/project.json
apps/analog-preset-e2e/project.json
apps/astro-app-e2e-playwright/project.json
apps/astro-app/project.json
apps/blog-app-e2e-cypress/project.json
apps/blog-app/project.json
apps/create-analog-e2e/project.json
apps/docs-app/project.json
apps/nx-plugin-e2e/project.json
apps/trpc-app-e2e-playwright/project.json
apps/trpc-app/project.json
libs/card/project.json
libs/top-bar/project.json
nx.json
packages/astro-angular/project.json
packages/content-plugin/package.json
packages/content-plugin/tsconfig.json
packages/content/ng-package.json
packages/content/project.json
packages/create-analog/project.json
packages/nx-plugin/project.json
packages/platform/project.json
packages/router/project.json
packages/trpc/project.json
packages/vite-plugin-angular/project.json
packages/vite-plugin-nitro/project.json

fix(content): adjust project config

---

packages/create-analog/index.js
packages/create-analog/template-blog/package.json
packages/create-analog/template-blog/src/app/app.config.ts

No prompt for syntax highlighter
Closes #
Prompt for syntax highlighter after `blog` template is selected or if `--template=blog` is passed in then default to `prismjs` for highlighter

feat(create-analog): syntax highlighter value for blog template

---

apps/create-analog-e2e/tests/create-analog.spec.ts
packages/create-analog/index.js

fix(create-analog): modify app config after the file is added

---

packages/create-analog/index.js

Closes #
When `yarn` is used, Nx peer dependencies are explicitly added to the project package.json because peer deps are not installed with `yarn` by default.

fix(create-analog): add dependencies based on template and package manager

---

packages/nx-plugin/src/generators/app/lib/initialize-analog-workspace.ts

the analogjs repo has an rxjs version of 7.8.0, we should install the same version when initializing a new nx analog workspace.
outdated rxjs version is installed
Closes #
same rxjs version as in main repo is installed

fix(nx-plugin): update rxjs dependency

---

README.md

Fixes the Nx logo in the readme

fix: nx logo in readme

---

apps/docs-app/docs/integrations/angular-material/index.md

Closes #
It features syntax that was used in earlier Angular Material versions
It features syntax that is used in the latest Angular Material version
- about prettier, I tried
not sure why it's failing

docs: update latest content of style.scss in Angular Material guide

---

apps/docs-app/docs/integrations/ionic/index.md

Related: https://github.com/eduardoRoth/analog-ionic-capacitor-template/issues/2
Closes #
Triumphant

docs: add lines needed for vitest and ionic integration

---

packages/platform/src/lib/content-plugin.ts

Closes #
- Lazy loads highlighter based on the selected one

fix(platform): lazy load highlighters

---

packages/content/prism-highlighter/src/index.ts

Closes #
Fixes existing usage of additional `prismjs` plugins on the client. In the future, we may make this change to be done manually, or moved to the build-time plugins.

fix(content): import prismjs on client for prism highlighter

---

apps/docs-app/docs/features/testing/vitest.md
packages/create-analog/template-angular-v16/angular.json
packages/create-analog/template-angular-v17/angular.json
packages/create-analog/template-blog/angular.json
packages/create-analog/template-latest/angular.json
packages/nx-plugin/src/generators/app/lib/add-analog-project-config.ts
packages/nx-plugin/src/generators/init/lib/update-test-target.ts
packages/nx-plugin/src/generators/setup-vitest/files/src/test-setup.ts__template__
packages/nx-plugin/src/generators/setup-vitest/lib/update-test-target.ts
packages/nx-plugin/src/utils/versions/dev-dependencies.ts
packages/nx-plugin/src/utils/versions/ng_15_X/versions.ts
packages/nx-plugin/src/utils/versions/ng_16_X/versions.ts
packages/nx-plugin/src/utils/versions/ng_17_X/versions.ts
packages/nx-plugin/src/utils/versions/ng_18_X/versions.ts

feat: setup Vitest with standalone vitest-angular package

---

packages/nx-plugin/src/generators/init/generator.ts

fix(nx-plugin): set nx variable for init file template

---

packages/create-analog/template-angular-v16/package.json
packages/create-analog/template-angular-v17/package.json
packages/create-analog/template-blog/package.json
packages/create-analog/template-latest/package.json
packages/vitest-angular/package.json
release.config.cjs

fix(create-analog): add vitest-angular to package.json deps

---

apps/ng-app/src/app/pages/posts.[slug].page.analog
packages/content/src/lib/markdown.component.ts

Closes #
When using `.agx` files, the component is rendered correctly

fix(content): filter out string content when using agx files

---

apps/docs-app/package.json
pnpm-lock.yaml

Closes #
Syntax highlighting for code blocks in docs works correctly

docs: update build and fix syntax highlighting

---

packages/astro-angular/src/index.ts
packages/vite-plugin-angular/src/lib/angular-build-optimizer-plugin.ts
packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
packages/vite-plugin-angular/src/lib/compiler-plugin.ts

Closes #
- Adds an environment variable when used with Astro
- Fixes a build issue when used with Astro Starlight

fix(astro-angular): add better support for Astro environment detection

---

package.json
packages/platform/package.json
packages/platform/src/lib/deps-plugin.ts
packages/platform/src/lib/platform-plugin.ts
packages/platform/src/lib/router-plugin.ts
pnpm-lock.yaml

Closes #1046
Instead of manually tracking dependencies that need to be added to the `noExternal` array, this relies on the `vitefu` package to crawl and discover Angular packages that should be transformed during SSR and pre-optimized in development. It respects existing configurations that define `noExternal` and `optimizeDependencies`.

feat(platform): add support for auto-discovery of SSR and optimization dependencies

---

packages/platform/src/lib/content-plugin.ts
packages/platform/src/lib/deps-plugin.ts
packages/platform/src/lib/router-plugin.ts
packages/router/src/lib/endpoints.ts
packages/router/src/lib/route-config.ts

fix(platform): adjust transform filters for routes

---

libs/shared/feature/src/pages/test.server.ts
packages/router/src/lib/routes.ts
packages/vite-plugin-nitro/src/lib/options.ts
packages/vite-plugin-nitro/src/lib/plugins/page-endpoints.ts
packages/vite-plugin-nitro/src/lib/utils/get-page-handlers.ts
packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts

Closes #
- Improves support for detecting server endpoints for page routes in shared folders.

fix(router): correctly discover page endpoints from additional sources

---

packages/vitest-angular/package.json

Closes #1249
Supporting `vitest` version 2

chore(vitest-angular): add vitest@2 to peerDependencies

---

packages/platform/src/lib/content-plugin.ts
packages/platform/src/lib/router-plugin.ts

fix(platform): normalize paths for finding page routes

---

package.json
packages/content/project.json
pnpm-lock.yaml

fix: crossplatform remove command

---

packages/router/src/lib/routes.ts

fix: additional dir paths windows

---

apps/blog-app/src/app/app.config.server.ts
apps/blog-app/src/main.server.ts
apps/blog-app/vite.config.ts
libs/shared/feature/src/pages/about-me.page.ts
libs/shared/feature/src/pages/about-you.page.analog

chore: add example ts/analog page routes from shared libraries to blog-app

---

apps/docs-app/docs/packages/create-analog/overview.md

The create-analog documentation page as not been updated for a while,e including outdated info.
Closes #1235
The template list is updated and the Tailwind mention was removed as its installation is part of the command now.

docs(create-analog): update documentation

---

apps/docs-app/docs/integrations/ionic/index.md

Adds a minor detail for Ionic apps in the index file

docs: add index meta tags to ionic guide

---

apps/docs-app/docs/experimental/sfc/index.md

Closes #
Added link to VSCode extension for AnalogJS Language Tools

docs: add link to VSCode extension for Analog Language Tools

---

apps/docs-app/docs/features/deployment/providers.md

docs: zerops guide

---

packages/vite-plugin-nitro/src/lib/utils/register-dev-middleware.ts

Closes #
- When middleware returns a value, do not process further middleware.

fix(vite-plugin-nitro): prevent handling further middleware on return

---

apps/docs-app/docs/integrations/storybook/index.md
apps/docs-app/sidebars.js
packages/vite-plugin-angular/src/lib/angular-storybook-plugin.ts
packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

Closes #1096
Adds a guide on migrating a Storybook with Angular using Vite instead of Webpack.

docs: add guide for using Storybook and Angular with Vite

---

apps/docs-app/docs/features/api/og-image-generation.md

Closes #
- remove h3 imports as Nitro auto imports it
- fix queryParam to match the og-images.ts file example using title

docs(content): review og-image docs

---

apps/docs-app/docs/features/routing/content.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/routing/content.md

Add section in the prismjs highlight paragraph of content routes about the style.
For new comer of prismjs, they don't know the full steps until checkout the prismjs documents. Adding the stylesheet is a mandatory step to add prismjs highlight in analogjs.

docs: update prismjs section in content routes

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

Closes #
Errors and warnings are surfaced on the client in development mode

fix(vite-plugin-angular): correctly capture diagnostics from errors and warnings

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

Revert "fix(vite-plugin-angular): correctly capture diagnostics from errors and warnings"

---

packages/create-analog/files/analog-env.d.ts
packages/create-analog/files/tailwind.config.cjs

Closes #
Analog SFCs are supported when Tailwind is selected without any additional changes.

fix(create-analog): add Analog SFCs to Tailwind config

---

apps/docs-app/docs/features/data-fetching/server-side-data-fetching.md
apps/docs-app/docs/features/deployment/overview.md
apps/docs-app/docs/features/deployment/providers.md
apps/docs-app/docs/features/generation/code-generation.md
apps/docs-app/docs/features/server/server-side-rendering.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/generation/code-generation.md

docs(content): requireSync note, ssr root route, app generation, and custom URL prefix

docs: add requireSync note, ssr root route, app generation, and custom URL prefix

---

apps/ng-app/src/app/app.component.analog
apps/ng-app/src/app/hello.analog
packages/vite-plugin-angular/src/lib/authoring/__snapshots__/analog.spec.ts.snap
packages/vite-plugin-angular/src/lib/authoring/analog.spec.ts
packages/vite-plugin-angular/src/lib/authoring/analog.ts
packages/vite-plugin-angular/src/lib/authoring/constants.ts

well...with a refactored analog file parser
Closes #1381 
supports `outputFromObservable`

fix(vite-plugin-angular): support outputFromObservable

---

packages/nx-plugin/src/generators/app/files/tailwind/latest/tailwind.config.ts__template__

Closes #1404
Styles work out of the box when tailwind is configured on project generated using nx-plugin.

fix(nx-plugin): added missing import for 'join' in tailwind template

---

packages/router/src/lib/request-context.ts

Closes #
- The transfer state cache key is not dependent on the URL origin
- Server-side data fetching requests are correctly handled by transfer state on first request

fix(router): serialize transfer state cache key for internal API requests

---

apps/docs-app/i18n/de/docusaurus-plugin-content-docs/current/features/api/og-image-generation.md
apps/docs-app/i18n/de/docusaurus-plugin-content-docs/current/features/api/websockets.md
apps/docs-app/i18n/de/docusaurus-plugin-content-docs/current/features/routing/middleware.md
apps/docs-app/i18n/de/docusaurus-plugin-content-docs/current/integrations/storybook/index.md
apps/docs-app/i18n/de/docusaurus-plugin-content-docs/current/packages/create-analog/overview.md
apps/docs-app/i18n/de/docusaurus-plugin-content-docs/current/sponsoring.mdx
apps/docs-app/i18n/de/docusaurus-plugin-content-docs/current/support.md

This PR adds german translation for following doc pages:
- `features/api/og-image-generation`
- `features/api/websockets`
- `integrations/storybook/index`
- `packages/create-analog/overview`
- `support`
- `features/routing/middleware`
This PR updates german translation for following doc pages:
- `sponsoring`

docs: update german docs

---

apps/docs-app/docs/features/routing/middleware.md

Closes #
I hope I understood well the documentation :D I found a typo about middlewares.

fix: use defineEventHandler when definining middlewares

---

packages/vite-plugin-angular/src/lib/angular-vitest-plugin.ts
packages/vitest-angular/builders.json

Closes #
The `schema` path for the `test` builder is correct.

fix(vitest-angular): fix path to schema.json for test builder

---

libs/card/src/lib/autocomplete/__snapshots__/autocomplete.component.spec.ts.snap
libs/card/src/lib/autocomplete/autocomplete.component.html
libs/card/src/lib/autocomplete/autocomplete.component.scss
libs/card/src/lib/autocomplete/autocomplete.component.spec.ts
libs/card/src/lib/autocomplete/autocomplete.component.ts
libs/card/src/lib/autocomplete/index.ts
packages/vite-plugin-angular/src/lib/angular-vitest-plugin.ts

Closes #
Removes set of default packages that causes test failures when downleveled

fix(vite-plugin-angular): remove default additional angular packages for testing

---

apps/docs-app/docs/guides/forms.md
apps/docs-app/src/css/custom.css

Closes #
- Updates docs for form server actions

docs(router): update docs for form server actions, embed video

---

nx.json
package.json
packages/nx-plugin/project.json

Closes #
Re-enables Nx cache for tests
Builds still WIP

build: partially re-enable Nx cache

---

apps/docs-app/i18n/es/code.json
apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current.json
apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current/support.md
apps/docs-app/i18n/es/docusaurus-theme-classic/navbar.json
apps/docs-app/src/pages/index.tsx

Closes # N/A
- Add translation for the "Support" section
- Add translation to Navbar item : Support
- Add translation to Partner for Deployments section

docs(content): translate support.md and partner for deployment section

---

packages/vite-plugin-nitro/README.md

Closes #
Updates the README for `@analogjs/vite-plugin-nitro` to show usage and example with React, Solid, and Vue.

docs(vite-plugin-nitro): update README with example for React, Vue, and Solid

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

Closes #1288
External templates and styles are resolved correctly when the vite plugin is registered multiple times, using a combination of JIT being enabled and disabled.

fix(vite-plugin-angular): resolve JIT external template/style files

---

packages/vite-plugin-angular/src/lib/authoring/__snapshots__/analog.spec.ts.snap
packages/vite-plugin-angular/src/lib/authoring/analog.spec.ts
packages/vite-plugin-angular/src/lib/authoring/analog.ts

fix(vite-plugin-angular): process destructured objects

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

Closes #
- HMR updates aren't sent on the initial page load, preventing double component rendering.
- Fixes support for setting `isSelfAccepting` flag with Vite 6.

fix(vite-plugin-angular): invalidation fixes for HMR/live reload

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

revert "fix(vite-plugin-angular): fix HMR of component styles"

---

release.config.cjs

Closes #
The nx-plugin versions are updated through semantic release

build: update release config to bump deps in nx-plugin

---

apps/docs-app/docs/features/deployment/providers.md

docs: improve github actions deployment guide

---

packages/create-analog/template-blog/package.json
packages/create-analog/template-latest/package.json
packages/create-analog/template-minimal/package.json

fix(create-analog): add overrides for Vite 6/Vitest 3 to templates

---

packages/create-analog/template-blog/angular.json
packages/create-analog/template-latest/angular.json
packages/create-analog/template-minimal/angular.json

Closes #
Fixes an issue where the root `dist` is resolved incorrectly by the `@nx/vite` executor.

fix(create-analog): set root in angular.json for templates

---

packages/astro-angular/README.md

Closes #
Documentation is added to control which files are transformed by Angular compilation when integrating into other environments, such as Astro and Starlight.

docs(astro-angular): add docs on filtering file transforms with Astro

---

package.json
packages/astro-angular/project.json
packages/content/project.json
packages/create-analog/project.json
packages/platform/project.json
packages/router/project.json
packages/vite-plugin-angular/project.json
packages/vite-plugin-nitro/project.json
packages/vitest-angular/project.json
release.config.cjs

Closes #
When versioning and publishing, only build the release packages.

build: only build packages during release job

---

.github/workflows/ci.yml

ci: bump artifact actions to v4

---

packages/vite-plugin-angular/src/lib/host.ts

The Angular compiler will trigger `readResource` for every `agx` file whenever a file changes. This becomes a problem, especially for sites with a larger amount of content files, as the markdown transforms re-run for every single content file on every change. With the current implementation, on a site with about 150 content files, this leads to a wait time of around 10 seconds for every change during development.
This adds caching to `readResource` for agx files. The modified time of the file is checked, and if it is unchanged since the file was last processed it will use the content from the cache.
Now on a file change, the markdown transforms only need to run for the one file that was changed. This also has the small side benefit that since we process agx files twice to generate the …

fix(vite-plugin-angular): cache resource reads for agx files

---

.github/workflows/ci.yml
package.json
pnpm-lock.yaml

Closes #
Bumps Vitest to 3.0.5 to fix security vulnerability

build: bump Vitest to 3.0.5

---

apps/analog-app/src/app/app.component.ts
apps/analog-app/src/app/cart.service.ts
apps/analog-app/src/app/pages/(home).page.ts
apps/analog-app/src/app/pages/[...slug].page.ts
apps/analog-app/src/app/pages/cart.page.ts
apps/analog-app/src/app/pages/client/(client).page.ts
apps/analog-app/src/app/pages/products.[productId].page.ts
apps/analog-app/src/app/pages/search.page.ts
apps/analog-app/src/app/pages/shipping/[...slug].page.ts
apps/analog-app/src/app/pages/shipping/index.page.ts
apps/analog-app/src/app/pages/shipping/shipping.html
apps/analog-app/src/app/pages/shipping/shipping.scss
apps/analog-app/src/app/product-alerts/product-alerts.component.ts
apps/analog-app/src/server/components/hello.ts

This PR updates the project to align with Angular v19 improvements:
Updated to new control flow to leverage the latest Angular features.
Removed standalone: true as it is now the default behavior in Angular v19.
Made dependency injection (DI) readonly for better immutability and code safety.

Refactor: Update to New Control Flow, Remove standalone: true, and Make DI Readonly

---

apps/docs-app/docs/features/testing/vitest.md
apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current/features/testing/vitest.md
packages/vitest-angular/README.md

Update the documentation to reflect extra setup lines for zoneless apps with vitest

docs: add extra instructions to use vitest in zoneless apps

---

apps/docs-app/docs/guides/compatibility.md

docs: update version compatibility

---

apps/docs-app/docs/integrations/angular-material/index.md
apps/docs-app/docs/integrations/storybook/index.md
packages/vite-plugin-angular/README.md

docs: update Angular Material and Storbyook integration guides

---

apps/docs-app/docs/features/deployment/overview.md
apps/docs-app/i18n/de/docusaurus-theme-classic/footer.json
apps/docs-app/i18n/es/docusaurus-theme-classic/footer.json
apps/docs-app/i18n/fr/docusaurus-theme-classic/footer.json
apps/docs-app/i18n/ko/docusaurus-theme-classic/footer.json
apps/docs-app/i18n/pt-br/docusaurus-theme-classic/footer.json
apps/docs-app/i18n/tr/docusaurus-theme-classic/footer.json
apps/docs-app/i18n/zh-hans/code.json
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current.json
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/api/websockets.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/data-fetching/server-side-data-fetching.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/deployment/overview.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/deployment/providers.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/routing/middleware.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/routing/overview.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/server/server-side-rendering.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/testing/vitest.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/guides/compatibility.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/guides/forms.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/integrations/angular-material/index.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/packages/astro-angular/overview.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/packages/vite-plugin-nitro/overview.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/sponsoring.mdx
apps/docs-app/i18n/zh-hans/docusaurus-theme-classic/footer.json

- Update Simplified Chinese document translation since last time
- Fix label Sponsor -> Sponsoring at footer
- Update the order on deployment section: [Deploying with a Custom URL Prefix](https://analogjs.org/docs/features/deployment/overview#deploying-with-a-custom-url-prefix)
Keep Simplified Chinese document update-to-date

docs: update zh-hans docs and fix some document issues

---

apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/deployment/overview.md

Remove the duplicated point 1 in [Custom URL Prefix Deployment](https://analogjs.org/zh-hans/docs/features/deployment/overview#%E9%83%A8%E7%BD%B2%E6%97%B6%E8%87%AA%E5%AE%9A%E4%B9%89-url-%E5%89%8D%E7%BC%80)

docs: remove duplicated point 1 on custom url prefix deployment

---

packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts

Closes #
When using the `NITRO_APP_BASE_URL` in development, the API routes are prefixed correctly.

fix(vite-plugin-nitro): handle Nitro Base URL for API routes in development

---

package.json
packages/platform/package.json
packages/vite-plugin-nitro/package.json
packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.ts
pnpm-lock.yaml

feat(vite-plugin-nitro): update nitropack to 2.11.x

---

zerops.yaml

Closes #1669 
The static deploy doesn't need redirects

docs: remove redirects from docs deployment

---

packages/vite-plugin-angular/src/lib/utils/hmr-candidates.ts

fix hmr issue

---

commitlint.config.cjs
packages/storybook-angular/package.json

fix(storybook-angular): only include explicit deps in package.json

---

apps/docs-app/docs/guides/compatibility.md
apps/docs-app/docs/integrations/storybook/index.md

Closes #
- Updates documentation on supported versions of Angular.
- Provides more clarity on Nx Devkit usage in Analog.

docs: update Angular version compatibility guide

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

Closes #
When running Vitest inside the Vitest VSCode extension, we defer initial compilation until we need to transform a file, then full initial compilation is done. This allows the extension to queue projects and provide more immediate feedback, providing a better developer experience.
The initial compilation is still done upfront for applications and running Vitest directly.

fix(vite-plugin-angular): defer initial compilation in Vitest VSCode extension

---

apps/docs-app/docs/integrations/storybook/index.md
packages/storybook-angular/README.md

Closes #
Updates instructions for using Angular & Vite w/Storybook and adds section for file replacements.

docs: update guide for Storybook integration

---

zerops.yaml

also fixes pnpm i asking for a yes prompt by adding CI=true to build envs

ci: cleanup Zerops build config

---

apps/analog-app/vite.config.ts
packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts
packages/vite-plugin-angular/src/lib/live-reload-plugin.ts
packages/vite-plugin-angular/src/lib/models.ts
packages/vite-plugin-angular/src/lib/utils/hmr-candidates.ts

Closes #1733 
- Live reload works correctly when enabled without startup errors.
- HMR eligibility still needs more tweaking, but can be improved later.

fix(vite-plugin-angular): fix live reload and move to separate plugin

---

.github/workflows/test-release.yml
apps/docs-app/docs/features/generation/code-generation.md
apps/docs-app/docs/guides/migrating.md
apps/docs-app/docs/integrations/nx/index.md
apps/docs-app/i18n/de/docusaurus-plugin-content-docs/current/features/generation/code-generation.md
apps/docs-app/i18n/de/docusaurus-plugin-content-docs/current/guides/migrating.md
apps/docs-app/i18n/de/docusaurus-plugin-content-docs/current/integrations/nx/index.md
apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current/guides/migrating.md
apps/docs-app/i18n/es/docusaurus-plugin-content-docs/current/integrations/nx/index.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/features/generation/code-generation.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/guides/migrating.md
apps/docs-app/i18n/zh-hans/docusaurus-plugin-content-docs/current/integrations/nx/index.md
apps/nx-plugin-e2e/tests/nx-plugin.spec.ts
packages/nx-plugin/README.md
packages/nx-plugin/generators.json
packages/nx-plugin/src/generators/init/lib/update-index-html.ts
packages/nx-plugin/src/generators/init/lib/update-package-json.ts
packages/nx-plugin/src/generators/init/lib/update-serve-target.ts
packages/nx-plugin/src/generators/preset/generator.ts

fix(nx-plugin): update Angular migration command and scripts

---

packages/vite-plugin-nitro/src/lib/plugins/dev-server-plugin.ts

fix(vite-plugin-nitro): resolve SSR entry point in subdirectory

---

packages/create-analog/package.json

fix(create-analog): add angular-v19 template to output files

---

packages/vite-plugin-nitro/src/lib/utils/get-page-handlers.ts

fix(vite-plugin-nitro): fix page handler URLs

---

packages/create-analog/index.js
packages/create-analog/template-blog/package.json
packages/create-analog/template-latest/package.json
packages/create-analog/template-minimal/package.json

fix(create-analog): update template package.json deps

---

packages/nx-plugin/src/generators/app/generator.ts

fix(nx-plugin): fix platform server dep for new app

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

Closes #1805
Fixes a performance regression introduced with the refactor to support large workspaces. Previously when the dev server starts up, it didn't emit files until the first request was made. The current behavior is to emit all files upfront, causing significant delay in startup time. This restores the previous behavior while keeping the memory footprint low for large workspaces when running Vitest.

perf(vite-plugin-angular): decrease dev server startup time by emitting files on demand

---

packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts

Closes #1811 
Live reload works correctly after saving changes.

fix(vite-plugin-angular): update file emitter after compilation

---

packages/storybook-angular/preset/preset.mjs

Closes #1809 
With Angular v20.1, the `@angular/platform-browser` package needs to be optimized for Storybook to run correctly.

fix(storybook-angular): add platform-browser to optimized dependencies

---

packages/content/resources/src/content-files-resource.ts
packages/content/src/lib/markdown.component.ts

Closes #
When using content resources for lists and content, the content is rendered correctly during SSR,

fix(content): fix server-side rendering with content resources
